### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by e-t-l** [brismuth/google-voice-bulk-texter#100]
**Is your feature request related to a problem? Please describe.**
Would it be possible to make a version of this extension for Firefox?

**Describe the solution you'd like**
The same extension, but compatible with Firefox.

**Describe alternatives you've considered**
To use this extension, I have to start up Chrome, which I rarely use and always works extremely slowly on my computer. It would be nice to be able to access this extension in my native browser.

**Additional context**
Thanks!

**Comment by brismuth** [comment]
After a quick glance at some guides for porting extensions, it looks like this may not be very difficult, assuming Firefox supports all the APIs I'm using. I'll try this out when I have the chance and report back on this thread if it works out.

**Comment by brismuth** [comment]
@e-t-l, I've uploaded the extension as a Firefox add-on. Right now the add-on is pending review, and once Mozilla has completed that it will be available to install at this link:

https://addons.mozilla.org/en-US/firefox/addon/bulk-texter/

I hope it's helpful for you!

**Comment by brismuth** [comment]
The add-on is now live on the Firefox store.

Enjoy!
