### ISSUE TITLE
Bulk SMS texting with Google Voice and Excel Offered by Bismuth   :)

### ISSUE THREAD

**Issue by ElaineAlbright** [brismuth/google-voice-bulk-texter#101]
I have been searching for hours for Google Voice Bulk Texter
I just discovered it was created by you!!!  I did not see that yesterday or today.  Oh! well, it is those 75 year old eyes, I guess!

TimEtzel has an Excellent Video on using your Program , However, it does not show up in the Google Chrome Store.  Is there a way of getting your Extension?  I would greatly appreciate it. Hopefully I can put this all together.  I am excited that I have been on GitHub touring around.  I am learning a lot reading all the threads.

Here is the Printscreen that Tim Shared but I have had no luck in finding the Chrome Extension, however,  I have had Bigger and Better Luck in finding You.  :)  I would appreciate any help in connecting with your Chrome Extension you can give me.

![image](https://user-images.githubusercontent.com/57522318/68465904-360b0400-01c8-11ea-85a6-0c291dc1b393.png)

 I am excited and look forward to your reply.  
Cheers, Elaine

Bulk SMS texting with Google Voice and Excel
8,090 views•Nov 8, 2018
SHARE

SAVE
timetzel
34 subscribers

Send 100's of personalized SMS texts to students and parents using Google Voice and Excel.

**Comment by brismuth** [comment]
You can find installation instructions here:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it

It was removed from the chrome web store but it is not too difficult to install manually, just follow those directions. 

Good luck!

**Comment by ElaineAlbright** [comment]
Hi! Brian,
Thank you for sharing your Bulk Texter for Google Voice.  I have installed
everything but I am having a little problem.  I can't figure out what it
is.  I have watched Tim Etzel's video (
https://www.youtube.com/watch?v=mVi7C9XpI6E&t=201s  ) probably 40
times,(not kidding, need to do this as I had a stroke so I am retraining my
brain paths  using CBD and by  transcribing every word so I can go by it
while watching his video and I have gone step by step, but there must be
something that I am missing.  I have the excel workpage done exactly as he
directs and everything looks perfect (to me anyway) haha.  However, I
cannot  get it to send the message to my phone or to the 2nd number
either.

I am working on it from my laptop.  Does that make a difference?

This is a sample of the sms message that I am trying to send attached.

It seems so simple but there must be one little thing I am not doing
correctly.

Any light you can shed I will be very grateful.

I have spent hours with this and I'm almost there but not quite and can't
figure it out.

Thanks, Brian for taking your time.

Cheers, Elaine

**Comment by brismuth** [comment]
The sample didn't come through - make sure you're posting on github directly rather than responding via email, as email won't copy in your attachments.

As far as debugging your issue with the bulk texter, I'd recommend starting with a simple message. For example, for the message, you could put "Test" and for the number you could just enter your own phone number. You can then add more complex messages and names once you get that working.

Good luck!
