### ISSUE TITLE
Error: "fillNumberInput" failed

### ISSUE THREAD

**Issue by doybird** [brismuth/google-voice-bulk-texter#102]
I have not been able to send any bulk messages with the app. When I click "Send Message," the page returns an message saying: "Error: "fillNumberInput" failed."

I tried to enter the phone number in various formats, to check and see if that was the issue, and no luck. For example, some different formats I tried were:

(555) 555-5555
(555) 555 5555
555-555-5555
555 555 5555
5555555555

I also tried adding a comma after each number and it did not work.

I'm using the Firefox extension within the web version of google voice at https://voice.google.com/

Thank you

**Comment by astein81** [comment]
I'm having the exact same issue.

**Comment by doybird** [comment]
I downloaded the extension and followed the steps to set it up for the Chrome browser, and it works fine in Google Chrome. But yeah, it does not work in Firefox (for me).

**Comment by ElaineAlbright** [comment]
Yes, I understand you must use Google Chrome extension

**Comment by ElaineAlbright** [comment]
it is now working for me.   Google also has words that are banned.  So, If
you have a message, start with the first word of the message then add 2
more words at a time.  That is how I found the banned words.
So, those words you cannot use in your message  Hope that helps.

**Comment by brismuth** [comment]
I haven't been able to reproduce this with the Firefox extension. It's possible that Google is rolling out a UI update, in which case the extension would need to be updated to support the new changes.

As soon as the changes show up on my account I'll be able to update the extension for them.

**Comment by ElaineAlbright** [comment]
Thanks, Brian
👍

**Comment by doybird** [comment]
> I haven't been able to reproduce this with the Firefox extension. It's possible that Google is rolling out a UI update, in which case the extension would need to be updated to support the new changes.
> 
> As soon as the changes show up on my account I'll be able to update the extension for them.

It's actually working fine on Google Chrome. It's the Firefox extension which isn't working for me. I prefer Chrome anyway, but figured I'd report the issue anyway. Thank you!

**Comment by rebecca122** [comment]
I' m having a problem When I click "Send Message," the page returns an message saying: "Error: "fillNumberInput" failed."

**Comment by brismuth** [comment]
I'm still not able to reproduce this issue on Chrome or Firefox.

@rebecca122 can you include a screenshot of the error message?

**Comment by CGKarate** [comment]
I have 2 profiles on Google Voice One for the business and one personal.  The Business profile does not work.

**Comment by brismuth** [comment]
@CGKarate are you saying this is the error message you get when you try to use google voice with the business profile?

**Comment by dustinb42** [comment]
![image](https://user-images.githubusercontent.com/60374722/73232290-9a8a8f00-4137-11ea-85ec-305362b302dc.png)

**Comment by dustinb42** [comment]
I'm using firefox

**Comment by brismuth** [comment]
@dustinb42 are you using Google Voice for Business or a free account?

**Comment by dustinb42** [comment]
Free account

**Comment by brismuth** [comment]
I just tried with my own account on both Chrome and Firefox and am still unable to reproduce this. 

Are all of you getting this error while sending to standard 10 digit USA phone numbers?

**Comment by dustinb42** [comment]
Yes

**Comment by dustinb42** [comment]
I also couldn't get it to work in Chrome, it just had a cycling error as soon as I installed it.

**Comment by maelliott16** [comment]
Same issue  Google Voice in Chrome, Firefox and Edge (beta)

**Comment by brismuth** [comment]
It sounds like Google is probably updating the Google Voice interface. I haven't gotten the update yet, so the extension is still working for me and I'm not able to reproduce the issue or submit a fix yet.

If you're experiencing this issue and you want to submit a fix, you can follow these instructions to install the extension from source (https://github.com/brismuth/google-voice-bulk-texter#chrome-install-from-source).
Line 9 of this file is the one that needs to be updated: https://github.com/brismuth/google-voice-bulk-texter/blob/master/src/contentScripts/main.js#L9
You can use the Chrome element inspector to find a new working selector for the phone number input.

**Comment by vincentwetzel** [comment]
I'm also getting this error.

Google Voice free account
Win10
Firefox 73.0.1
Google Voice Bulk Texter v1.1.7

It navigates to the "TO:" field, a dropdown of suggested names appears, then the URL changes a few times but the UI remains the same, then the error window appears for "Error: "fillNumberInput" failed.".

**Comment by formanjacob** [comment]
I'm having the same problem. Nothing happens in Chrome and I get the same message in Firefox. The last time I used it was a few weeks ago and it worked fine. My wife also has a google voice free account and she does not have the problem even though I'm using the same computer.

I'm not sure if there is anything I can help you with for troubleshooting, but I'd be happy to send you any information you need.

Thank you for the extension. It has been a timesaver for me.

**Comment by brismuth** [comment]
Sorry, without being able to reproduce this issue on my own computer it will be hard for me to resolve it.

**Comment by Ssnos** [comment]
I use your extension every day.  Today I started getting the message that everyone is talking about in Firefox.

**Comment by brismuth** [comment]
I'm getting this error in Firefox now as well - that means I should be able to figure out what's going on finally and upload a fix.

**Comment by Ssnos** [comment]
Great.  I really like your add-in and have come to rely on it😊  I have been trying the Chrome version, which works but doesn’t like dashes (-)?
THANK YOU!
Susan

**Comment by Ssnos** [comment]
I take that back.  There seems to be a length limit on the chrome extension.  I hope it can be fixed.

**Comment by brismuth** [comment]
This fix is a little more tricky than I hoped - I'm looking into it and I'm entirely not sure what the change is on the Google Voice side that has stopped it from working. I'll update here when I figure it out though.

**Comment by brismuth** [comment]
I've spent several hours looking into this and I'm at a loss - the extension relies on pasting the number into that input in order to trigger the phone number dropdown. For some reason the extension is unable to paste into that particular input now. The extension is still able to paste in the message field, just not in the number search field.
Without that working, I'm not sure of another way to trigger the phone number dropdown to update - it stays stuck on favorites instead of updating and showing the number it just typed in.

**Comment by Ssnos** [comment]
Ok.  That’s a shame.  I tried to use chrome and it seems to limit the length of the message.  I was using it for appointment reminders.  Do you know if there is a character limit in Chrome?
Thank you,
Susan

**Comment by brismuth** [comment]
There is no length limit in chrome. It’s more likely that with longer messages, Google Voice is flagging you for potential spam. 

See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md

**Comment by Ssnos** [comment]
No, it just reloads the 1st entry over and over.  If I shorten the message it works.  They are appointment reminders so that are a bit long.

**Comment by brismuth** [comment]
Just circling back on this - in Firefox 77.0.1 this issue no longer appears to be occurring.

If people are still seeing the "fillNumberInput" error after updating Firefox, reach out and I'll reopen the issue.

**Comment by mnjosephttx3** [comment]
I'm getting this error with the latest firefox addition. Attempted to format in different ways.  It opens the contact list but doesn't select the number and fails with the error.
