### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by afantazi1** [brismuth/google-voice-bulk-texter#103]
Hi account continues to loop on the first number without moving to the second number. On previous attempts it did go past the first number then began looping on the second number. I also tried this extension about a year ago and had the same issue. I've also tried using different Google Voice accounts but I'm having the same issue. Do you know how this can be resolved?

**Comment by afantazi1** [comment]
![2019-12-04_1756](https://user-images.githubusercontent.com/46008354/70191534-0ec02d80-16c7-11ea-8314-88ef6eedab2b.png)
![2019-12-04_1756](https://user-images.githubusercontent.com/46008354/70191554-1f70a380-16c7-11ea-839d-60d4aa584901.png)

**Comment by afantazi1** [comment]
Here's a snapshot of my setup... in this instance the app texted the first number then continued to loop on the second number, never reaching any of the remaining numbers.

**Comment by brismuth** [comment]
Are you getting any error messages when the loop ends? 

Also, what version are you on? It looks like you cropped the version out of your screenshots.

**Comment by ElaineAlbright** [comment]
To your question or comment,  I had the same thing happen.  I simply
deleted the first # and clicked OK and the batch went perfectly.  I had the
same thing happen in a different batch and I deleted that number and the
balance of the texts went just fine.  That is  google chrome  that I used.
Hope this helps.

**Comment by afantazi1** [comment]
this is the error I have
![2020-01-28_1309](https://user-images.githubusercontent.com/46008354/73296226-446d2880-41d7-11ea-88fa-0800a5067aa3.png)

**Comment by brismuth** [comment]
@afantazi1 are you on Google Voice for business or a free account?

**Comment by afantazi1** [comment]
I am on a free account. I’ve also tried multiple different free accounts.

**Comment by brismuth** [comment]
To clarify - you've experimented with trying multiple accounts, and it always loops on the second number and gives you the "startChat" failed error?

Have you tried shorter messages or anything like that?
