### ISSUE TITLE
Error when sending out messages

### ISSUE THREAD

**Issue by Eleni2** [brismuth/google-voice-bulk-texter#107]
Hi 
When sending out my messages I am getting the following error

<b>Error:`  This message was not successfully delivered.</b>

Do you know of any issues or do you have any fixes?

Thanks

**Comment by brismuth** [comment]
Please read the support page. 

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
