### ISSUE TITLE
not sending

### ISSUE THREAD

**Issue by maelliott16** [brismuth/google-voice-bulk-texter#109]
if (messageEditor.value && messageEditor.value !== message) {
			console.log('Bulk SMS - Already had value:', messageEditor.value);
			return;
		}

		if (messageEditor && messageEditor.offsetParent !== null) {
			messageEditor.value = message;
			return true;
		}
	}

	sendMessage() {
		var messageEditor = document.querySelector(selectors.gvMessageEditor);
		if (!messageEditor) {
			return;
		}

		messageEditor.focus();
		messageEditor.select();
		document.execCommand('cut');
		document.execCommand('paste');

		// click send button
		let sendButtonOld = document.querySelector(selectors.gvSendButtonOld);
		let sendButtonNew = document.querySelector(selectors.gvSendButtonNew);
		if (sendButtonOld && sendButtonOld.offsetParent !== null && sendButtonOld.getAttribute('aria-disabled') === 'false') {
			sendButtonOld.click();
			return true;
		}
		if (sendButtonNew && sendButtonNew.offsetParent !== null && sendButtonNew.disabled === false) {
			sendButtonNew.dispatchEvent(new Event('mousedown'));
			sendButtonNew.dispatchEvent(new Event('mouseup'));
			sendButtonNew.click();
			return true;
		}
	}

	confirmThreadHeaderUpdated() {
		let chatLoadedHeader = document.querySelector(selectors.gvChatLoadedHeader); // the header switches to this after sending is complete. If we move on before this, it can break things.
		if (chatLoadedHeader) {
			return true;
		}
	}

	confirmSent() {
		let sendingNote = document.querySelector(selectors.gvSendingNote); // this is the note that says "Sending", it will disappear when it is finished

		if (!sendingNote) {
			// check if the message we sent is showing up in the chat window
			let mostRecentMessages = document.querySelectorAll(selectors.gvMostRecentMessages);
			let	sentMessageIsThreaded = false;
			if (mostRecentMessages && mostRecentMessages.length) {
				var i = mostRecentMessages.length - 1;
				for (i; !sentMessageIsThreaded && i >= 0; i--) {
					let mostRecentMessage = mostRecentMessages[mostRecentMessages.length - 1];
					sentMessageIsThreaded = mostRecentMessage.innerText === this.messagesToSend[this.currentNumberSending];
				}
			}

			if (sentMessageIsThreaded) {
				logEvent({
					eventLabel: 'MESSAGE_SENT',
					eventValue: 1
				});
				// continue with queue
				const timeBeforeNextMessage = getRandomWaitTimeMS(6000);
				setTimeout(this.sendFromQueue.bind(this), timeBeforeNextMessage);
				return true;
			}
		}
	}
}

**Comment by brismuth** [comment]
You seem to have copied a section of the extension code instead of describing your issue.
