### ISSUE TITLE
"startChat" Failed

### ISSUE THREAD

**Issue by anthonydp801** [brismuth/google-voice-bulk-texter#110]
**Describe the bug**
Whenever I attempt to send a text to more than one person, it enters the first number in and then never sends the first message. A few seconds later it gives me the error "startChat" Failed.

**URL**
https://voice.google.com/u/2/messages?itemId=draft-02D09A6C-BFF3-4167-8B67-ACD8BD773421

**Expected behavior**
I used it once before and it sent 2 messages before it crashed. I just need it to actually send the texts so I don't have to enter it all myself

**Screenshots**
<img width="447" alt="Screen Shot 2020-02-06 at 9 26 37 PM" src="https://user-images.githubusercontent.com/60765114/73995864-fe773980-4927-11ea-94b7-bc2fb334bd0e.png">

**Additional context*
I read through previous support tickets in which you told them to install the newest update, but I believe I have the newest update 1.1.6.

**Comment by brismuth** [comment]
Is this still happening for you consistently?
