### ISSUE TITLE
Messages not sending

### ISSUE THREAD

**Issue by czakon123** [brismuth/google-voice-bulk-texter#115]
The first number will pop up like it's about to send but it will just stay there and never send any texts.

**Comment by jf-boop** [comment]
I have the same problem starting today

**Comment by jf-boop** [comment]
![Issue](https://user-images.githubusercontent.com/61806987/75929146-f4b8f700-5e3d-11ea-86ce-48870fb43473.PNG)

**Comment by brismuth** [comment]
This is a duplicate of #111. I'll update the title of that issue so that's easier to find. :) 

You'll want to subscribe to that issue so you get updates when it is resolved.
