### ISSUE TITLE
Keeps looping send over the first line phone number - formatted correctly

### ISSUE THREAD

**Issue by TXTFox** [brismuth/google-voice-bulk-texter#116]
**Describe the bug**
Keeps looping send over the first line phone number - formatted correctly
**URL**
google voice
**Expected behavior**
It was working flawlessly for a day - then now when using again it just keeps trying to send the top line number. It just loops continuously and doesn't send anymore.

**Screenshots**

**Additional context**

**Comment by TXTFox** [comment]
Still same issue. After 30 texts works fine. When we try to send another list of numbers with a full list of just 5 numbers in....
It starts looping back to the first line.
Is there any way to slow the deployment?
This isnt sp#m. But seems they think it is

**Comment by brismuth** [comment]
Please see the support page (especially the linked section):
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed

**Comment by TXTFox** [comment]
We know that. This is a small list of dedicated clients we have had for over 10 years. This isnt spam. Not by far. 
 Is there a way for us to slow down the send time so it doesnt go every 4-5 seconds? That is what we are asking.
