### ISSUE TITLE
Google voice audio message

### ISSUE THREAD

**Issue by joethered72** [brismuth/google-voice-bulk-texter#117]
**Is your feature request related to a problem? Please describe.**
Not a problem with the current feature - curious as to the ability to modify program to call and play a mp3 file as a type of robocall.

**Describe the solution you'd like**
I would like to be able to call numbers and have a message played. I make welcome calls for an online class and it is usually the same message and it would be better to automate instead of repeating the phone call multiple times.

**Describe alternatives you've considered**
There are companies that pay for this feature, but since I work at a school I would rather not pay out of pocket 

**Additional context**
My coding experience is limited, so I am not sure how much would have to change to play a message instead of sending a text

**Comment by brismuth** [comment]
I don't think this is possible to do - the Chrome extension is limited to what APIs browsers make available, and as far as I'm aware there's no API for hooking in and spoofing the microphone, which would be what was needed for this.
