### ISSUE TITLE
Bulk text not sending to Verizon carrier?

### ISSUE THREAD

**Issue by GBCDenver** [brismuth/google-voice-bulk-texter#118]
Sent a bulk text to appox. 120 contacts, those that are on Verizon (that we can verify) did not receive the message the GV interface shows the message populated and attempted to send but simply says "Not sent." 

Suggestions?

**Comment by jkhdesign** [comment]
I'm having the same issue where Verizon users aren't receiving my messages. That said - they're still displaying as sent within Google Voice. I wonder if Verizon is attempting to block it as a spam message somehow?

**Comment by brismuth** [comment]
If Google Voice shows them as sent, there's nothing this Chrome extension can do to fix the issue.

You could try reaching out on the Google Voice support forums.
