### ISSUE TITLE
Message failed to send. I have been using this for about a month and it's been wonderful, but it stopped working for me yesterday. I can't even send a single text. I downloaded the newest version, deleted cookies and caches and it still won't work. Any ideas? 

### ISSUE THREAD

**Issue by StephMWright** [brismuth/google-voice-bulk-texter#119]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dctian** [comment]
i think it is because google voice blocked you (from server side), because Google thinks you are spamming.  try to send a text message via your hangout/google voice phone app (not via this browser extension), can your text go through?

**Comment by StephMWright** [comment]
Thanks, it ended up working. I appreciate your help.

Stephanie Wright
stephmwright71@gmail.com <mailto:stephmwright71@gmail.com>
703-973-8775

**Comment by StephMWright** [comment]
I am having issues with the bulk tester. It stopped working three days ago. It says the chat failed to start. Any ideas on what to do?

Thanks,

Stephanie Wright
stephmwright71@gmail.com <mailto:stephmwright71@gmail.com>
703-973-8775

**Comment by brismuth** [comment]
Is this still happening for you?

What browser are you using?

**Comment by StephMWright** [comment]
It’s working! Thank you so much!

Stephanie Wright
stephmwright71@gmail.com <mailto:stephmwright71@gmail.com>
703-973-8775
