### ISSUE TITLE
Test message to 2 people not sending

### ISSUE THREAD

**Issue by kevdogsiberia** [brismuth/google-voice-bulk-texter#12]
**Describe the bug**
I am trying to send a test message out to two people, and neither are receiving the message. They show as sent in my message history online though. 

**URL**
https://voice.google.com/u/1/messages?itemId=draft-FD04AEA4-A6A4-4DE5-925F-0D94DAAF0005 

**Expected behavior**
I expected the two people to get the text.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by brismuth** [comment]
@kevdogsiberia can you try sending messages manually (without the extension)? From what you're saying it sounds like Google Voice itself isn't working for you, and if that's the case it's something you'll have to resolve with Google. The extension just works on top of Google Voice and can't fix any underlying issues there may be with it.

**Comment by kevdogsiberia** [comment]
I did already try sending the message manually, and it works fine.

**Comment by brismuth** [comment]
So you're saying that if you send it manually or with the extension, either way it shows up in your message history, right?

But if you send with the extension it doesn't arrive on their phone? That's really bizarre, I can't imagine what would cause that.

**Comment by brismuth** [comment]
That's odd, I send links pretty regularly with it and haven't had any issues. Let me know if you keep having issues with this and you think they're on the Chrome extension side (and not the Google Voice service side).

Thanks!
