### ISSUE TITLE
Sending time

### ISSUE THREAD

**Issue by TXTFox** [brismuth/google-voice-bulk-texter#120]
**Is your feature request related to a problem? Please describe.**
Any way to have the sending take 15 seconds - or delay the send....  It goes too fast.
**Describe the solution you'd like**
Make the send time random or where we can adjust
**Describe alternatives you've considered**
Change code so we can send out the msgs every [x] seconds.
**Additional context**
Any way to have the sending take 15 seconds - or delay the send....  It goes too fast.

**Comment by brismuth** [comment]
I've added support for custom delays in the latest version of the extension! 

You can update to version 1.3.1 by following these instructions:
https://github.com/brismuth/google-voice-bulk-texter#update-it
