### ISSUE TITLE
console.error('Bulk SMS - ' + fullMessage); - Version 1.2.0

### ISSUE THREAD

**Issue by smhennes** [brismuth/google-voice-bulk-texter#121]
When sending messages, it gets to the 2nd or 4th message and then hangs up.  When I remove the numbers that have already been sent to, it does continue however only does 2-4 messages and hangs up.

Bulk SMS - Google Voice bulk texter v1.2.0: Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom. Error: "confirmSent" failed. When you click "ok" the page will refresh.
Context
https://voice.google.com/u/0/messages?itemId=draft-0C76AA72-11EA-419F-8C87-A87C9A40EF6C
Stack Trace
contentScripts/tools.js:87 (showFatalError)
contentScripts/tools.js:36 (anonymous function)

/**
 * removes all non-numeric characters from the number string
 * @param  {string}   number i.e. +1 (223) 456-7890
 * @return {string}         i.e. 2234567890
 */
function formatNumber(number) {
	var simplifiedNumber = number.trim().replace(/\D/g,'');
	// remove international code for US numbers
	if (simplifiedNumber.length === 11 && simplifiedNumber.charAt(0) === '1') {
		simplifiedNumber = simplifiedNumber.substr(1);
	}
	return simplifiedNumber;
}

function getFunctionName(func) {
	return func.name.replace(/bound /g, '');
}

/**
 * continually calls the given method until successful
 * @param {Function}   method         should return true when successful, or false when we should give up early
 * @param {bool}       silenceErrors  true if we should not alert on errors
 * @param {Function}   cb             to be called with the results from method when we're done trying
 */
function keepTrying(method, silenceErrors, cb) {
	const frequency = 100; // try every 100ms
	let tryCount = 5 * 1000/frequency; // keep trying for 5 seconds
	var keepTryingInterval = setInterval(function() {
		var successful = method();
		var giveUp = successful === false || tryCount-- < 0;
		if (successful === true || giveUp) {
			clearInterval(keepTryingInterval);
			// the app failed
			if (!silenceErrors && giveUp) {
				if (siteIsGoogleVoice) {
					showFatalError(`You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.\n\nError: "${getFunctionName(method)}" failed.`, true);
				} else {
					showFatalError('Are you sure Google Voice texting via Hangouts is enabled?\nAlso, be aware that this extension is not compatible with the Google Hangouts Chrome extension. If you have the Hangouts extension installed you\'ll need to temporarily disable it.', false);
				}
			}
			if (cb) {
				cb(successful);
			}
		}
	}, frequency);
}

/**
 * continually calls the given method until successful
 * Promisified for use with async/await
 * @param {Function}   method         should return true when successful, or false when we should give up early
 * @param {bool}       silenceErrors  true if we should not alert on errors
 * @param {Function}   cb             to be called with the results from method when we're done trying
 */
function keepTryingAsPromised(method, silenceErrors) {
	console.log('Bulk SMS - Running: ', getFunctionName(method));
	const waitTime = getRandomWaitTimeMS(300)
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			keepTrying(method, silenceErrors, (successful) => {
				resolve(successful);
			});
		}, waitTime);
	});
}

/**
 * Gets a random time in ms between 500 and (max + 500) for waiting
 * @return {Number}
 */
function getRandomWaitTimeMS(max) {
	return Math.floor(Math.random() * max) + 500;
}

/**
 * shows the message as an alert, reloads the page if instructed to
 * @param {*} message
 * @param {*} reload
 */
function showFatalError(message, reload) {
    if (siteManager) {
        siteManager.messagesToSend.length = 0;
    }
    const manifest = chrome.runtime.getManifest();
	const reloadMessage = '\n\nWhen you click "ok" the page will refresh.';
	const fullMessage = `Google Voice bulk texter v${manifest.version}:\nText failed. ${message} ${reload ? reloadMessage : ''}`;
	**_console.error('Bulk SMS - ' + fullMessage);_**
	alert(fullMessage);
    if (reload) {
        window.location.reload();
    }
}

/**
 * Sends a message to background.js for storage (usage tracking for future user-visible dashboards, and anonymous data for developer)
 * @param  {object} payload  the google analytics payload
 */
function logEvent(payload) {
	chrome.runtime.sendMessage({
		gvbt_logger: true,
		payload: payload
	});
}

/**
 * Removes unicode characters from the text
 */
function removeUnicode(text) {
	return text.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
}

/**
 * Removes whitespace from the text
 */
function removeWhitespace(text) {
	return text.replace(/\s/g,'');

}

**Comment by brismuth** [comment]
Please see the support page, there is a writeup on "confirmSent" failed and this behavior:

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
