### ISSUE TITLE
Bulk Texter not working 

### ISSUE THREAD

**Issue by Ickstar009** [brismuth/google-voice-bulk-texter#122]
I am trying to send a mass text and the first number listed begins to dial and loop until it stops.  This message is what pops up:

Google Voice bulk texter v1.2.0:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "writeMessage" failed. 

When you click "ok" the page will refresh

Does anyone have an idea why this is occuring?

It does allow me to send single texts either through the bulk texter or the google voice app?

Thanks!

**Comment by Byronnn** [comment]
I have the same problem and only checked your issue to see if someone solved the problem. Looks like no one answered you. If you somehow found a solution email me at carriereb71@gmail.com

**Comment by StephMWright** [comment]
I am also having this issue. I can send single texts, but not multiple people. Thanks.

**Comment by brismuth** [comment]
What browser are you using? Looks like Chrome is working fine for me right now.
