### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by certifiedali** [brismuth/google-voice-bulk-texter#124]
Hii Guys ,I get this notification , how to solve it ?
(Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "confirmSent" failed. 

When you click "ok" the page will refresh.)

**Comment by brismuth** [comment]
Please read the support page:

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed

**Comment by certifiedali** [comment]
i dont know about that ,but i reinstalled extension its working fine for me , so is it normal ? and i have one more question ,how do i abort the messages once they are being sent

**Comment by brismuth** [comment]
Read the support page. 

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#tips
