### ISSUE TITLE
Is it possible to add a random interval to the product？

### ISSUE THREAD

**Issue by s100020595** [brismuth/google-voice-bulk-texter#125]
**Is your feature request related to a problem? Please describe.**
The fixed interval is not very good. Because normal people can’t control the interval for each message to be 1 minute or 2 minutes.

**Describe the solution you'd like**
Is it possible to add a random time within a certain range to the software? For example, send a message within one to five minutes

**Describe alternatives you've considered**

**Additional context**

**Comment by brismuth** [comment]
What is the benefit to it being random instead of fixed?

**Comment by s100020595** [comment]
I think Google may detect the time interval，My account has just been
suspended, I’m not sure if it has anything to do with this interval. I
think you can consider my suggestion, it should be easy for you.

Brian Smith <notifications@github.com> 于2020年8月9日周日 上午11:17写道：

**Comment by s100020595** [comment]
I think Google may detect the time interval，My account has just been suspended, I’m not sure if it has anything to do with this interval. I think you can consider my suggestion, it should be easy for you.

**Comment by brismuth** [comment]
It seems unlikely that this will help meaningfully, vs spacing out your messages more.
