### ISSUE TITLE
Only First Phone Number Gets My Message

### ISSUE THREAD

**Issue by educatoral** [brismuth/google-voice-bulk-texter#127]
Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "confirmSent" failed. 

When you click "ok" the page will refresh.

**Comment by brismuth** [comment]
I don’t control account limits or spam detection - Google does. 

Please read the support page for recommendations:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
