### ISSUE TITLE
Not sending bluck text on Firefox saying "not sent" Learn more.... or Message failed to send....even with i try to send an individual message not a large group 

### ISSUE THREAD

**Issue by sdpromisemiramar** [brismuth/google-voice-bulk-texter#128]

**Comment by sdpromisemiramar** [comment]
Not able to send bulk text anymore on Firefox using the add on

**Comment by brismuth** [comment]
I don’t control account limits or spam detection - Google does. 

Please read the support page for recommendations:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
