### ISSUE TITLE
edge case: sends second message twice

### ISSUE THREAD

**Issue by danielneill** [brismuth/google-voice-bulk-texter#129]
Description: 
First time user, but was testing and found it quickly.
URL: https://voice.google.com/u/0/messages
Browser:  latest Chrome
OS: Win10, latest updates

Workflow:
1. Use extension to send to me, not my real number in this writeup, but was my actual cell number. default delay of 5s.
(123) 456-7890, Dan Neill
2. It works (EXPECTED), window closes.
3. Open extension again, same number, name recipient list is in the pane (EXPECTED)
4. Add a second line below this one, with the same phone number (mine), but a fake name
(123) 456-7890, Bob Smith
5. EXPECTED -> sends two texts to me, one will say "Hi Dan Neill", the other "Hi Bob Smith", 5s apart
ACTUAL -> sends two texts to me, first says "Hi Bob Smith", the other "Hi Bob Smith", 5s apart

Priority:
Not sure, will add more if I need to use it and it matters.  Offhand I can't think why I would ever use this exact workflow.

**Comment by brismuth** [comment]
Thanks for reporting. 

If someone ever actually needs this workflow I’ll look at refactoring some things to support it.
