### ISSUE TITLE
Error Message (account suspended?)

### ISSUE THREAD

**Issue by KaylyM** [brismuth/google-voice-bulk-texter#130]
**Describe the bug**
"ConfirmSent" error message. 

**URL**
https://voice.google.com/u/0/messages?itemId=draft-E041912E-E738-4EEB-9ACE-E56ED6EF77F8

**Expected behavior**
Expected to have multiple texts sent in sequence as they were before, but instead it would send one at a time. Other sites are suggesting account suspension, but I am a teacher using to message parents and not spamming! I have tried shortening my message, and no links are included. 

**Screenshots**

**Additional context**

**Comment by kmolyneuxuos** [comment]
I have had the same issue. I am a teacher hoping to send texts to my students/parents but it suspended my account for 24 hrs after I tried to send to too many students.

**Comment by brismuth** [comment]
I don’t control account limits or spam detection - Google does. 

Please read the support page for recommendations:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
