### ISSUE TITLE
Bulk texttin

### ISSUE THREAD

**Issue by safraw** [brismuth/google-voice-bulk-texter#131]
I work for Indeed Hire and we use bulk text to assist in reaching out multiple candidates at a time. Is there anyways my profile could be adjusted so i dont get blocked when sending mass texts.. My coworker reached out and was able to get assistance with this. The email associated is safrawague@gmail.com

**Comment by brismuth** [comment]
I don’t control account limits or spam detection - Google does. 

Please read the support page for recommendations:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
