### ISSUE TITLE
Wrong phone number-  Written in box correctly but sends to different numbers.

### ISSUE THREAD

**Issue by Krugma** [brismuth/google-voice-bulk-texter#132]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Krugma** [comment]
Wrong phone numbers.  They are copied into box correctly, but send to different numbers.

**Comment by brismuth** [comment]
I haven’t seen this or heard of this happening before. 

You’re saying that it’s sending to different numbers than the ones you’ve put in the box?

Is it happening for every number you put in? Any chance you can get a video of it happening?

**Comment by Krugma** [comment]
It happened 2 times, then went back to normal.   If it happens again, I'll video.



Marilyn Krug
Guitar 1, Music of the World, Peer Counseling 1

Seminole County Public Schools
Seminole County Virtual School
450 Technology Park
Lake Mary, FL 32746
Office Phone: 407-720-9628
________________________________

**Comment by brismuth** [comment]
Sounds good, thanks.
