### ISSUE TITLE
bypass area codes such as 896 and 841 that cause silent failure mid-batch

### ISSUE THREAD

**Issue by timweb** [brismuth/google-voice-bulk-texter#133]
These area codes (896 and 841) do not seem to correspond to real phone numbers.  Ideally, the system would flag and bypass them.

At the very least, a warning should be provided, either at run-time or at install-time.

Currently (I last checked a few months ago), they make it stop/fail with no indication of the reason.

There's probably a whole list or class of such area codes, but I've only encountered those two.

**Comment by brismuth** [comment]
This tool is intended for texting people that you know personally who have given you their phone number.

Where are you getting phone numbers with fake area codes?
