### ISSUE TITLE
Manifest issue

### ISSUE THREAD

**Issue by CoachGal** [brismuth/google-voice-bulk-texter#134]
**Describe the bug**
I used the Bulk Voice texter about a month ago and sent too many texts (was trying to send a message to all of my students' parents).  I got cut off and then I decided to delete the extension from Chrome.  I cannot, for the life of me, install it back.  I keep getting an error message about the Manifest.

**URL**
googlevoice.com

**Expected behavior**
Install the Bulk Texter extension

**Screenshots**
Here is the error message:
Failed to load extension
File
~\Desktop\google-voice-bulk-texter-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Additional context**
I need to find the simplest way to fix this - I am a teacher who knows little to nothing about coding!

**Comment by brismuth** [comment]
Make sure you are selecting the correct folder to load when you install the extension. It needs to be the “src” folder - not just the top level folder. That’s usually what causes this issue.
