### ISSUE TITLE
Feature Request - Automated Dialling

### ISSUE THREAD

**Issue by rnarayan** [brismuth/google-voice-bulk-texter#135]
Brian,

I love this extension and I have been using this for two years to communicate with my employees. 

I was thinking today if a feature (or a separate extension) can be added to automate dialing a few numbers until someone picks up the phone. It's a personal need. For every client that I have, they can have different numbers (different personnels) and I ended up spending a significant amount of time just dialing different numbers until I can reach one of them.

I know some JS. With some guidance, I can take a shot at it too. I went through your code but couldn't understand where would I begin to implement such a feature.

**Comment by brismuth** [comment]
Looking at how Google Voice handles phone calls, I don't see any way of detecting whether or not a phone call is answered (vs hanging up after ringing or going to voicemail).

Dialing could be automated, but without the other portion I don't see that being very useful.
