### ISSUE TITLE
Won't let me use on firefox on lenovo computer.

### ISSUE THREAD

**Issue by clarench** [brismuth/google-voice-bulk-texter#136]
**Describe the bug**
As I use google sheets on my 2018 Lenovo laptop, the extension wont run - instead it tells me to make sure I'm signed into Google Voice which I always am including the fact that I'm ensuring that the accounts are aligned - and yes I have a Google call number- but still no luck. It then gives me an option to troubleshoot and that's all she wrote. 

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
> As I use google sheets on my 2018 Lenovo laptop
This extensions only works on Google Voice, not on Google Sheets.

**Comment by brismuth** [comment]
To clarify, Make sure you are currently on the Google Voice site (https://voice.google.com/) and click the extension while you are on the site.
