### ISSUE TITLE
Do not use this extension: it goes against Google ToS, your Voice account will be suspended

### ISSUE THREAD

**Issue by simleknight** [brismuth/google-voice-bulk-texter#137]
I used this code as intended. After the first time, I got a warning, but thought it was just a problem with the code. After the second time, I got the warning again, and my Voice account was suspended. Voice support stated clearly that no bulk texting is allowed, not even if done by hand. Do not use this extension; it may have worked in the past, now it will get your account suspended. I have been without my Voice account now for two weeks after several appeals. Not worth risking use.

**Comment by dfmartinvii** [comment]
@simleknight 
How short were your times in between messages?
I'm pretty quick at sending messages manually, but 5 seconds (the default value) is way too fast and likely set off Google's alarms.

Also, what were you using it for? That matters. If you were doing something that Google thought was spammy, then that might have been why they actually banned you.

**Comment by simleknight** [comment]
Here is exactly what occurred:

I used the default settings to send 44 texts (wasn't aware that other
settings adjustments were needed), it sent to five or six numbers. Message
was something regarding building safety. There was an error, I didn't
understand it, but thought it was because I navigated away from the screen.
Redid the send, it did include the original 5-6 recipients, the same error
occurred this time after maybe 15 texts, and then the account immediately
(apparently automatically) suspended.

Subsequent messages from Voice forums "official" (and sometimes rude)
community folks confirms that using this tool at all is against ToS.

**Comment by brismuth** [comment]
The tool requires you to agree that you have read and understand Google Voice's acceptable use policy before using it:
https://support.google.com/voice/answer/9230450?hl=en&ref_topic=9273222

Many users use this tool successfully without their account being banned.

I recommend reading error messages, check boxes, and terms of service for any software that you use - you are less likely to run into trouble that way. Regardless, this software is provided free of charge, and you are welcome to use it or not use it as you see fit.

Best of luck!
