### ISSUE TITLE
Text Failed msg

### ISSUE THREAD

**Issue by Khanirsh** [brismuth/google-voice-bulk-texter#138]
**Describe the bug**
I got the error in the middle of sending my text msg.  I had about 25 phone numbers.  

This is what I got..  
"Text Failed. you can find the support resources by opening Google Voice bulk Tester popup and clicking "Get HELP" at the bottom. 

So what went wrong? 
Thanks for your help. 
Thanks, 
Irshad

**Comment by JJames0917** [comment]
I'm having the same problem 6 days later.  Please help.  Thank you!
Julie

**Comment by km-rgb** [comment]
I am getting the same error.  It will send 10-15 and then only inputs the phone number without inputting the message.  It will try the same phone number 2-3 times and then the below error pops up.
![image](https://user-images.githubusercontent.com/81381662/112517716-dded8700-8d55-11eb-9bf4-1c578b968dbf.png)

**Comment by brismuth** [comment]
This error is covered on the support page:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
