### ISSUE TITLE
Only Sending to First Recipient

### ISSUE THREAD

**Issue by rsfiandra** [brismuth/google-voice-bulk-texter#139]
Have used this extension before with no issues but now when I go to send it's only sending to the first recipient. No error messages after a bunch of tries. I have tested in Chrome and Firefox. Went as far as uninstalling extensions and also attempted to use smaller distribution list and smaller messages just in case the length of the message was triggering spam block. 

I looked up closed cases but it looks like everyone else that experienced this received error messages which I'm not.

**Comment by saltlaker** [comment]
I'm experiencing the the same issue.

**Comment by brismuth** [comment]
Is this still happening? I'm guessing this was due to some changes Google was testing out, assuming it's no longer occurring.

**Comment by crivera8602** [comment]
getting same error 
<img width="842" alt="Screen Shot 2021-07-14 at 1 26 30 PM" src="https://user-images.githubusercontent.com/63074950/125681006-64708b0c-29af-4180-87c6-ae72881556ec.png">

**Comment by brismuth** [comment]
@crivera8602 your issue is different, and is covered in detail in the support doc:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed

@rsfiandra specifically said they are not receiving an error message.

**Comment by brismuth** [comment]
@rsfiandra @saltlaker since I haven't heard back from you I'm going to go ahead and close this issue. If you're still experiencing the same behavior (failing with no error message) comment on this thread and I'll reopen it.
