### ISSUE TITLE
Externsion does not see Voice running

### ISSUE THREAD

**Issue by lizzy235** [brismuth/google-voice-bulk-texter#140]
**Describe the bug**
I run the extension form the voice.google.com page and the extensions throws the following report
Google Voice Bulk Texter
Unable to find Google Voice on the page.
Try some of the following options:
Make sure you are currently on Google Voice or Google Hangouts
Try refreshing the page
If it still isn't working for you, see additional troubleshooting tips here
.
I don't have google hangounts setup to receive or send texts

**URL**
https://voice.google.com/u/1/messages 

**Expected behavior**
expected to see the extesion open 

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Is this still happening? I'm guessing this was due to some changes Google was testing out, assuming it's no longer occurring.

**Comment by brismuth** [comment]
Going to close this as no other users have reported this issue. Feel free to comment on here again if it's still happening.
