### ISSUE TITLE
I'm getting an "Error: StartChat failed" message after sending my first few batches. Any ideas?

### ISSUE THREAD

**Issue by alex-macintosh** [brismuth/google-voice-bulk-texter#141]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by km-rgb** [comment]
I am getting thissame error

**Comment by brismuth** [comment]
Is this still happening? I'm guessing this was due to some changes Google was testing out, assuming it's no longer occurring.

**Comment by brismuth** [comment]
Actually, I'm guessing this is due to a poorly formatted number, like in
https://github.com/brismuth/google-voice-bulk-texter/issues/149
