### ISSUE TITLE
missing or corrupted manifest

### ISSUE THREAD

**Issue by JPremack** [brismuth/google-voice-bulk-texter#142]
Just downloaded extension but Chrome developer mode install failed with missing or damaged manifest error message. Any thoughts?

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Make sure you are selecting the right folder, you need to be selecting the `src` folder (i.e. inside it), not the folder above it.
