### ISSUE TITLE
Error: "fillNumberInput" failed.

### ISSUE THREAD

**Issue by mckayabrown** [brismuth/google-voice-bulk-texter#145]
Getting this error when trying to send bulk texts. 
"fillNumberInput" failed

Here is what the pop up screen says.

voice.google.com says
Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voic eBulk Texter popup and clicking "Get Help" at the bottom.

Error: "fillNumberInput" failed.

When you click "ok" the page will refresh.

**Comment by brismuth** [comment]
Is this still happening? I'm guessing this was due to some changes Google was testing out, assuming it's no longer occurring.

**Comment by brismuth** [comment]
If this is still happening, and you're using FireFox, try using Chrome. See #102 - there was a period where some FireFox changes broke the extension.
