### ISSUE TITLE
*67----quick fix to be added in this week ~~ perhaps!???

### ISSUE THREAD

**Issue by SonJ1** [brismuth/google-voice-bulk-texter#146]
I tried to insert *67 when putting in the numbers~~ but it reports an error  :'((

REALLY ...REALLY**** need this for my business for google voice because there is no other way for me to send these texts without people text me back X NO Thank you X and calling me back X NO Thank you X

**Couldn't this be a quick fix to be added in this week ~~ perhaps!???**

**Comment by brismuth** [comment]
I'm not supportive of this functionality - it sounds like functionality that would primarily benefit spammers.

Also, it's worth noting that Google Voice also blocks this, so even if I wanted to support it, I couldn't.

**Comment by SonJ1** [comment]
I see, thank you.
