### ISSUE TITLE
Texts will not send

### ISSUE THREAD

**Issue by DER0520** [brismuth/google-voice-bulk-texter#147]
I used this extension for a couple of hours and it worked well. That was 2 days ago. Now I am getting this message when I try to send texts:

"Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "confirmSent" failed. 

When you click "ok" the page will refresh."

Any idea of when this will be fixed? I am hesitant to fully trust this extension when I see so many issues being reported and not being responded to.

**Comment by marafa** [comment]
did u checkout the support ink? its the first line you pasted

**Comment by DER0520** [comment]
The support link just took me to a list of issues. Most were unanswered.

**Comment by brismuth** [comment]
@marafa is correct, the support page describes this exact issue, I recommend reading the entire page, but especially the section that has your error:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed

Thanks @marafa!
