### ISSUE TITLE
unknown error : startChat failed

### ISSUE THREAD

**Issue by marafa** [brismuth/google-voice-bulk-texter#149]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

after receiving this error. i found that firefox wanted to restart and would crash tabs until i restarted firefox.
![Screenshot_20210515_130835](https://user-images.githubusercontent.com/1518315/118378220-36941000-b5a0-11eb-8014-ae9e56b7482b.png)

**Comment by marafa** [comment]
nope. firefox restarted and i still got the same error on the very first number

**Comment by marafa** [comment]
oh! .. the number was missing a numeral

**Comment by brismuth** [comment]
Glad you got that sorted out!

**Comment by brismuth** [comment]
I'll actually go ahead and reference this issue in the support page too.
