### ISSUE TITLE
Accept other payment methods for supporting this project

### ISSUE THREAD

**Issue by CNBarnes** [brismuth/google-voice-bulk-texter#153]
Right now it looks as if you only accept Stripe as a way for people to help support this project and/or move suggested enhancements to a higher priority.

I would suggest adding Venmo  (free for person-to-person transfers).  This way, you get ALL of the money being donated.   And as a donation, it would not violate the Venmo TOS...  Personally, this addon saves me over $100/mo in what I was paying to a service... Giving you a month's worth of that is easy to do.

**Comment by brismuth** [comment]
Hi @CNBarnes - thanks for your suggestions on the other issues and for reaching out here.

My Venmo/PayPal are posted on the project readme and donations are welcome! ❤️
https://github.com/brismuth/google-voice-bulk-texter#donating

I saw a couple of other github projects (clearly more popular than mine, haha) where https://issuehunt.io was working really well at tying funding to specific issues, but it doesn't seem to be doing much on here. 🙂 
The downside with Venmo/PayPal is that they can't tie donations back to the individual issue pages.
