### ISSUE TITLE
google-voice-bulk-texter looping on single PH and failing 

### ISSUE THREAD

**Issue by vicks2020** [brismuth/google-voice-bulk-texter#155]
google-voice-bulk-texter is looping three times with single ph # and failing with below error..  I am able to send txt message individually.  I have set 1 mins delay between two txts msgs.  please help

Error: "confirmSent" failed

**Comment by brismuth** [comment]
Did you end up getting the extension to work for you?

**Comment by vicks2020** [comment]
Hello Brian  - Unfortunately it didn't work out.  Google started locking my
account even after a delay of up to 5 mins in between the text messages.
When I restarted after pausing for 24 hrs  to allow google to unlock my
account, it would send a couple of them and loop a few times on the same
email before failing..  So I kind of gave up. Any thoughts ?

Thanks for your valuable contributions to the community.

**Comment by brismuth** [comment]
Unfortunately I don't have much insight into Google's spam/abuse detection algorithms, but this does not appear to be widespread among users of the extension or more people would be reporting it. I'm guessing it may have been something in the content of your messages.

**Comment by vicks2020** [comment]
ok thanks Brian. The content is an invitation to a meditation webinar and
includes a zoom link to join. would that be an issue ?

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it
