### ISSUE TITLE
Can't not find Google voice page

### ISSUE THREAD

**Issue by GraceQianyun** [brismuth/google-voice-bulk-texter#156]
Hi there, i am novice in this bulk texting, when I stay on the Google voice page and open the Bulk SMS extension, It said "Unable to find Google Voice on the page. " , No matter how many times I refresh, It said same content, and I switch to Firefox also isn't working, Same problem.
I checked the Google extension page, this is the mistake shows on the Google Voice Bulk Texter1.3.2 extension, Please help
![519f36a9490af00df3d4ce996ccbf80](https://user-images.githubusercontent.com/96585309/147263622-b0274fdb-902b-480e-9758-8377239aa947.png)

**Comment by brismuth** [comment]
That’s odd. Maybe just try closing chrome (all the way) and reopening it after installing the extension? Haven’t seen this error before.

**Comment by GraceQianyun** [comment]
When I open  Google Hangouts, the dialog box appears successfully, but the Google Hangouts can not send SMS and the Google Voice still said  "Unable to find Google Voice on the page. "  :(

**Comment by brismuth** [comment]
Currently the extension only supports Google Voice with Google Voice set to English - that may be causing the issue.
