### ISSUE TITLE
Error: "confirmSent" failed.

### ISSUE THREAD

**Issue by instructorgirl** [brismuth/google-voice-bulk-texter#157]
**Describe the bug**
When I run the texter it doesn't copy and paste or confirm sent on the phone numbers.
**URL**
The URL you were on when the problem occurred. 
https://voice.google.com/u/0/messages?itemId=draft-351B6760-79FC-42DA-9367-71448506C0BA
**Expected behavior**
I'm expecting the texter to text the list of recipients. 
**Screenshots**

**Additional context**
![Google Voice Texter Error](https://user-images.githubusercontent.com/97633168/149215883-103daa5a-73f6-4ea5-a58f-59e32a183f74.PNG)

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it
