### ISSUE TITLE
Name not being included

### ISSUE THREAD

**Issue by stevec45** [brismuth/google-voice-bulk-texter#158]
**Describe the bug**
A clear and concise description of what the bug is.    I am trying to add a name to the phone number as shown in your directions and the email is being sent out but no name is being included.    I am using:  phone number, name   Is that the correct format?

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
@stevec45 you'll also need to include the placeholder for the person's name in the message body, as shown in the example. I recommend just starting with the exact text from the example and swapping the number out for your own phone number to experiment with it.

**Comment by stevec45** [comment]
Thank you!   I forgot to do that.     Steve
