### ISSUE TITLE
Question on sending to multiple contacts

### ISSUE THREAD

**Issue by LFFC96** [brismuth/google-voice-bulk-texter#159]
I couldn't find the answer to this question. How many contacts can I send in one "bulk" text? Also, do the receivers only see their number, and not the "groups" phone numbers as well?

**Comment by brismuth** [comment]
Not sure about the limit. Thousands, probably. The issue would be google flagging you for spam, more likely than the tool having issues. 

People will only see your number, not the rest, because it sends a message to each person instead of to a group.
