### ISSUE TITLE
This keeps occuring!! I don't know how to fix it and I desperately need this extension for teaching

### ISSUE THREAD

**Issue by kimberlyann0287** [brismuth/google-voice-bulk-texter#160]
Failed to load extension
File
~/Downloads/google-voice-bulk-texter-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by brismuth** [comment]
@kimberlyann0287 this error means that you are selecting the wrong folder or sub-folder when you're loading in the extension.
You'll want to review the installation instructions carefully and try them again, double checking that you're in the right folder, or alternatively you can use FireFox and use the extension from the FireFox extension store. https://addons.mozilla.org/en-US/firefox/addon/bulk-texter/
