### ISSUE TITLE
Google Bulk Texter is no longer working.

### ISSUE THREAD

**Issue by svenwilson** [brismuth/google-voice-bulk-texter#161]
It sends the first text, then stops. I am using the correct syntax (ex.  555-555-1212,555-555-1212 ), and have used both 2 and 5 second delays. 

I have also sent from different accounts and computers, and get the same result. 

Can anyone help? I really need this to work again.

**Comment by Cynthia1235566** [comment]
Hi

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it
