### ISSUE TITLE
New problem that I facing now

### ISSUE THREAD

**Issue by Any0930** [brismuth/google-voice-bulk-texter#167]
Why is the **Google Voice Bulk Texte**r not working properly for some of my Google accounts? The problem is that the first contact number is stuck, and the rest cannot be sent out? #Not every Google Voice Account is like this!

**Comment by redhookmutualaid** [comment]
Same!  Not sure how to resolve...

**Comment by Any0930** [comment]
Hope it can be solve quickly.

![image](https://user-images.githubusercontent.com/101367056/157995669-53f36c09-9993-4205-956a-920a42939020.png)

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it
