### ISSUE TITLE
ConfirmSent Failure

### ISSUE THREAD

**Issue by pcampio** [brismuth/google-voice-bulk-texter#168]
I get a confirmsent error after first text is sent preventing additional texts from going out.

Normally, it automatically goes to the next message and sends them all out 1 by 1.

I tried removing the extension and reloading it on chrome and vivaldi -- same error in both places makes me believe it's not a local error.

<img width="456" alt="Screen Shot 2022-03-14 at 1 06 36 PM" src="https://user-images.githubusercontent.com/53572217/158234564-77656af4-b345-455c-ab1f-1a1b6f8d74b8.png">

Additional context -- I think google voice updated recently and the code in the extension might need to be updated for it work going forward.

**Comment by redhookmutualaid** [comment]
Same problem - we use bulk texting to send out info to our community, so eager to resolve!

**Comment by meloncholia** [comment]
yes, same problem. also same as previous issue "looping on the same number". new install

**Comment by MMccombe2022** [comment]
Same problem today.  Loops on the same number and doesn't go to the next in the list.

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it

**Comment by pcampio** [comment]
Thank you for fixing! v1.3.3 works for me!
