### ISSUE TITLE
Looping on same phone number

### ISSUE THREAD

**Issue by apt173** [brismuth/google-voice-bulk-texter#169]
**Describe the bug**
The Google voice bulk texter is looping on the same phone number when trying to send message to multiple recipients.

Is anyone else experiencing this issue?

**Comment by vannahpy** [comment]
Yes, but last time I used it this wasn't an issue

**Comment by sricher7** [comment]
I am also having the same problem. It's been going on for a few days now.

**Comment by meloncholia** [comment]
new install. tried to send my first bulk and got this looping on the first email, then the error message same as ticket #168. help?

**Comment by bkamyszek** [comment]
Same issue here. Just posted a new ticket (should have read first, sorry)

**Comment by besariong** [comment]
Here's the fix, replace selector for gvMostRecentMessages in main.js with:

gvMostRecentMessages: 'gv-text-message-item gv-annotation',

and reload extension.

**Comment by brismuth** [comment]
Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. Check if there are any [open issues](https://github.com/brismuth/google-voice-bulk-texter/issues) reporting the issue already, and if there are, feel free to subscribe to them or comment on them.

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it

Please thumbs up this message if the fix works for you - and thanks @besariong for digging into the code!

**Comment by besariong** [comment]
@brismuth - you're welcome. Thank you for creating great tool!

**Comment by iliketoteach** [comment]
> Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):
> 
> > **Extension is looping on a single number and failing with an error message**
> > This is usually caused by Google Voice rolling out website changes in phases. Check if there are any [open issues](https://github.com/brismuth/google-voice-bulk-texter/issues) reporting the issue already, and if there are, feel free to subscribe to them or comment on them.
> 
> That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.
> 
> Follow the instructions here to update to v1.3.3: https://github.com/brismuth/google-voice-bulk-texter#update-it
> 
> Please thumbs up this message if the fix works for you - and thanks @besariong for digging into the code!

I followed the instructions, downloaded the new version, but the problem persists. Please help!

**Comment by iliketoteach** [comment]
I followed the instructions, downloaded the new version, but the problem persists. Please help! The messages are still looping on the same number.
