### ISSUE TITLE
Security & Logging Question

### ISSUE THREAD

**Issue by amandaddf** [brismuth/google-voice-bulk-texter#17]
Hello there!

I was excited to come across your extension as just today one of my clients was asking me to look into a bulk text solution for her, and it looks like your extension will be just what she's looking for. 

Myself & my client are always on high alert for security risks, so I wanted to ask quickly if you have a security or privacy policy related to the extension - do you log any phone numbers or message content, for example? 

Thank you so much for your time and for creating this!

Yours,

Amanda

**Comment by brismuth** [comment]
There are a couple paragraphs about data collection on the chrome extension listing:

Google Analytics Tracking:
- Data collected: an event each time the popup is shown, and an event each time the popup button is clicked, which includes the "to" count. 
- Contact information and messages are NOT collected.
- None of the information collected can be linked to your account or person, and the collected information is only used to improve the application.

**Comment by brismuth** [comment]
Feel free to reply on here if you have any additional questions. Thanks!
