### ISSUE TITLE
Can't confirm sent for first number

### ISSUE THREAD

**Issue by bkamyszek** [brismuth/google-voice-bulk-texter#171]
After running the extension, it stops after the first number because it cannot confirm the first message was sent. The rest of the list does not send. 
![image](https://user-images.githubusercontent.com/101895659/159065993-ca602a7b-6993-4204-85d0-d09139535028.png)

**Comment by brismuth** [comment]
See #169 - this should be resolved now.

Per the [support page](https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#extension-is-looping-on-a-single-number-and-failing-with-an-error-message):

> **Extension is looping on a single number and failing with an error message**
> This is usually caused by Google Voice rolling out website changes in phases. 

That is why this affected some people first, and gradually affected more people. Unfortunately, it's not affecting my account, so I am unable to test the fix suggested by @besariong, but I have applied @besariong's fix in v1.3.3.

Follow the instructions here to update to v1.3.3:
https://github.com/brismuth/google-voice-bulk-texter#update-it
