### ISSUE TITLE
Failed to load extension (chrome) 

### ISSUE THREAD

**Issue by ignitethenightproductions** [brismuth/google-voice-bulk-texter#175]
**Describe the bug**
could not install the google voice bulk texter 

Chrome://extensions
The URL you were on when the problem occurred. 

could not install the extension on Chrome after unzipping the folder.

MESSAGE to me was--> 
Failed to load extension
File
~/Downloads/google-voice-bulk-texter-master
Error
Manifest file is missing or unreadable
Could not load manifest.

thanks!!!
brian

**Comment by brismuth** [comment]
Double check that you're following the installation instructions - you need to select the `src` folder inside that folder.

**Comment by brismuth** [comment]
https://github.com/brismuth/google-voice-bulk-texter
