### ISSUE TITLE
Google Messages

### ISSUE THREAD

**Issue by vulfgang** [brismuth/google-voice-bulk-texter#176]
Could this be modified to work with messages by google? That can also be run from a browser and is connected to an actual number that may be able to circumvent spam reporting

**Comment by brismuth** [comment]
I have no plans to port the functionality myself, but you can take a look at this chrome extension that another user created that is based on mine and works with Google Messages:

https://github.com/zvakanaka/church-bulk-text

**Comment by vulfgang** [comment]
Appreciate that, this works great, to your knowledge how hard would it be to integrate being able to send images. Or to point to the first image when activating the image tab on google messages?

Any insight would be helpful.

Thanks again,
Nathan
________________________________
