### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Lucianna01** [brismuth/google-voice-bulk-texter#177]
![image](https://user-images.githubusercontent.com/104949765/168895611-ab4caeee-3370-47ed-b388-2bce251b12f3.png)
![image](https://user-images.githubusercontent.com/104949765/168896091-43c79f55-8802-4226-a0c7-43647c124d95.png)

**Comment by brismuth** [comment]
@Lucianna01 the manifest error is unrelated (it won't be an issue until 2023). 

Are you getting the fillNumberInput on every phone number? Have you tried testing with your own 10 digit phone number, for example?
