### ISSUE TITLE
Message Problem

### ISSUE THREAD

**Issue by cityl1fe** [brismuth/google-voice-bulk-texter#178]
**Describe the bug**
The extension is sending the message 2 to 3 times in 1 out of 5 messages.

**URL**
(https://voice.google.com/u/0/messages?itemId=t.%2B15049483011)

**Expected behavior**
The message being sent once per number.

**Screenshots**

**Additional context**
Would love to hear some troubleshoots for this if you guys have ever heard of this happening. I tried lower the seconds between messages down from 5 to 2 and it didnt help. 
![20220518_141917](https://user-images.githubusercontent.com/92239768/169140384-20c63b0c-bdfe-4f80-8600-8ef9ea7896ab.jpg)

![20220518_141817](https://user-images.githubusercontent.com/92239768/169140365-a59eee43-67da-418c-8445-4fb4e33acdd5.jpg)

![20220518_141903](https://user-images.githubusercontent.com/92239768/169140356-3b021705-af5c-4d49-b177-3c2bec7fa6bb.jpg)

![20220518_141824](https://user-images.githubusercontent.com/92239768/169140336-a8eb2740-0a94-411d-9d26-dc91c071e702.jpg)

**Comment by brismuth** [comment]
@cityl1fe these screenshots look like phishing/scamming. 
I will not provide any support to anyone using the tool like that, and I am not okay with the tool being used for illegal purposes. Please stop.
