### ISSUE TITLE
Help extention not working all of a sudden

### ISSUE THREAD

**Issue by cmiranda24** [brismuth/google-voice-bulk-texter#179]
Hi... when I put in phone number now and hit send it just shows this... 

Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:
Invalid phone number:

**Comment by brismuth** [comment]
I'd recommend starting with a simple example, such as your own phone number in the phone number field with no symbols (i.e. 1234567890) and a simple message to send (i.e. Hello), and see if that works. I'm not able to reproduce the issue, so I'm guessing it's an issue with the input.
