### ISSUE TITLE
Text failed

### ISSUE THREAD

**Issue by qwemnba** [brismuth/google-voice-bulk-texter#181]
Google Voice bulk texter v1.3.3:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "confirmSent" failed. 

When you click "ok" the page will refresh.

How to solve

**Comment by brismuth** [comment]
See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
Typically this means that Google Voice is blocking your messages, and I do not have any control over that.
