### ISSUE TITLE
Won't load Extension

### ISSUE THREAD

**Issue by CaryM2022** [brismuth/google-voice-bulk-texter#182]
When I follow the very clear instructions you provide and navigate to the folder for the extension, Chrome gives me this error message:

Failed to load extension
File
~\Downloads\google-voice-bulk-texter-master\google-voice-bulk-texter-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by brismuth** [comment]
@CaryM2022 you need to click into the `src` folder inside the google-voice-bulk-texter-master folder. That should resolve the issue.
