### ISSUE TITLE
 Error: "confirmSent" failed

### ISSUE THREAD

**Issue by Hug0max** [brismuth/google-voice-bulk-texter#184]
why I used this app before is not a problem but now it can not be used it show Error: "confirmSent" failed but the google voice is new id

**Comment by Hug0max** [comment]
![photo_2022-07-20_11-45-42](https://user-images.githubusercontent.com/109642774/179892432-2c010d83-b7d7-436e-9eb2-7be4a66a19c0.jpg)
this is the problem i get

**Comment by brismuth** [comment]
See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed
Typically this means that Google Voice is blocking your messages, and I do not have any control over that.
