### ISSUE TITLE
unable to load unpacked google voice bulk text extension: ERROR "Manifest file is missing or unreadable Could not load manifest."

### ISSUE THREAD

**Issue by ts4810** [brismuth/google-voice-bulk-texter#185]
**Describe the bug**
After extracting the zip drive and saving on my desktop, I attempted to load unpacked but received error: 
"Manifest file is missing or unreadable Could not load manifest."

**URL**
The URL you were on when the problem occurred. 
chrome://extensions/

**Expected behavior**
I was expecting the extension to load on my chrome.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/110223236/181709971-e116c54f-8590-494a-8b68-ac7c0e91e441.JPG)

**Additional context**

**Comment by brismuth** [comment]
@ts4810  you need to click into the `src` folder inside the google-voice-bulk-texter-master folder. That should resolve the issue.
