### ISSUE TITLE
confirmChatSwitched error occurring

### ISSUE THREAD

**Issue by WhiteOlive2020** [brismuth/google-voice-bulk-texter#186]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WhiteOlive2020** [comment]
confirmChatSwitched Is the code I get, how do I resolve?

**Comment by jherre14** [comment]
I'm having the same issue.  I was sending a text to about 30 people, but it just keeps trying to send it to the first number repeatedly without a 5 second delay.  After about 5 attempts, the error message appears, Error: "confirmChatSwitched" failed.

**Comment by brismuth** [comment]
This type of issue typically occurs when Google is changing their code. The extension will need to be updated to support their new code, but they roll it out in phases to different users, so I will not be able to fix it until the issue occurs for me (and it is not right now).

In the past, impacted users have filed a pull request with the fix - you can see this for an example:
https://github.com/brismuth/google-voice-bulk-texter/pull/82/files

**Comment by brismuth** [comment]
Here's another example of what the fix could look like: https://github.com/brismuth/google-voice-bulk-texter/pull/172/files

**Comment by brismuth** [comment]
`gvRecipientButton` is the selector that is no longer working that will need updated.

**Comment by Shawnarea** [comment]
Thank you for the info brismuth, guess we just have to wait patiently now🙏🏻

**Comment by brismuth** [comment]
Is this still happening for those of you that reported the issue?
@Shawnarea @jherre14 @WhiteOlive2020

**Comment by brismuth** [comment]
Closing this issue, per this report that the confirmedChatSwitched error is no longer occurring:
https://github.com/brismuth/google-voice-bulk-texter/issues/188#issuecomment-1238740422

Guessing it was a change that Google was experimenting with on their side and stopped rolling out.

**Comment by jherre14** [comment]
This issue has returned, the “confirmedChat Switched” failed error.

Joel Herrera
***@***.***

**Comment by brismuth** [comment]
Okay @jherre14, good to know. Let's track this on #193 - feel free to comment on there or click the button to subscribe to it.

**Comment by jherre14** [comment]
It has resolved. I believe that it resolved within two days. Thank you

Joel Herrera
________________________________
