### ISSUE TITLE
experiencing issues with Google Voice Bulk Texter

### ISSUE THREAD

**Issue by Shawnarea** [brismuth/google-voice-bulk-texter#187]
HlELP PLEASE.....When using bulk Texter its giving me an error :confirmChatSwitched" failed

Was working fine a last time i used it but its not here is a screen shot. 

![Screen Shot 2022-08-03 at 12 58 16 PM](https://user-images.githubusercontent.com/110561219/182677930-48d7a44f-b159-459c-9652-50123a0727e0.png)

**Comment by brismuth** [comment]
This is a duplicate of #186, feel free to post over there and follow that thread.
