### ISSUE TITLE
Getting error confirmChatSwitched - how do I resolve? 

### ISSUE THREAD

**Issue by DrewMagnet** [brismuth/google-voice-bulk-texter#188]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Is this still happening for you? Errors like this are usually caused by Google Voice rolling out website changes in phases.

**Comment by DrewMagnet** [comment]
I am good now
 Thanks for checking in!

**Comment by brismuth** [comment]
Glad to hear it!
