### ISSUE TITLE
Account suspended?

### ISSUE THREAD

**Issue by Julelongo10** [brismuth/google-voice-bulk-texter#189]
Hello, I am having trouble sending messages in the bulk texter area. I accidentally sent it to the same number multiple times by accident and I did not mean to and I think it thinks I am spaming. And now it is not letting me send messages in the bulk texter. It said "Error: Writemessage" failed. I do not know what to do or how to fix it. Please help.

**Comment by brismuth** [comment]
See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed - I do not have any control over whether Google flags you for spamming or suspends your account.
