### ISSUE TITLE
No longer can send text

### ISSUE THREAD

**Issue by Qxboxone** [brismuth/google-voice-bulk-texter#19]
I have had 0 issues up until now. When I click send it just gets stuck on the first number and never enters the text or sends then it eventually fails with error code "confirm sent failed"

**Comment by Qxboxone** [comment]
I discovered the issue it was an invalid phone number

**Comment by brismuth** [comment]
To confirm, it's working for you with no issues again now?

**Comment by Qxboxone** [comment]
Yes Brian thank-you sorry for the delay I love your add-on!

**Comment by Qxboxone** [comment]
Is it possible to create something like this for text now? A bot of sorts? I’d be interested.
