### ISSUE TITLE
Unable to find Google Voice on the page.

### ISSUE THREAD

**Issue by lactosefreemilch** [brismuth/google-voice-bulk-texter#190]
**Describe the bug**
Did everything and reresh th epage couple times but still the extension cant detect the voice page

**URL**
[The URL you were on when the problem occurred. ](https://voice.google.com/u/0/calls)

**Screenshots**
![image](https://user-images.githubusercontent.com/112069693/186613788-08bbc68e-af01-4682-b9ee-aeba1f9895ff.png)

**Comment by lactosefreemilch** [comment]
![Uploading image.png…]()

**Comment by brismuth** [comment]
Currently the extension only supports Google Voice with Google Voice set to English - that may be causing the issue.
