### ISSUE TITLE
Text Failed

### ISSUE THREAD

**Issue by jeanineredman** [brismuth/google-voice-bulk-texter#192]
When I'm using the bulk texting extension I get this error after a couple of failed loops for a particular number.  It worked for a few numbers but stopped mid-way through and will not continue.
<img width="435" alt="Screen Shot 2022-09-16 at 7 42 53 AM" src="https://user-images.githubusercontent.com/66073982/190631511-6521a808-1794-46c4-84ff-683bc3cdc711.png">

**Comment by brismuth** [comment]
See https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md#account-suspension--error-confirmsent-failed.
