### ISSUE TITLE
Failure - confirmchatswitched

### ISSUE THREAD

**Issue by Efficiency-super** [brismuth/google-voice-bulk-texter#193]
**Describe the bug**
Text send failed with error.

**URL**
The bulk-texter app. 

**Expected behavior**
Send should text to all recipients.

**Screenshots**
[https://ibb.co/pKY8c9F]

**Additional context**

**Comment by 2021msw** [comment]
how do I fix this error. I am needing to send out text immediatly.  Please help

**Comment by sculley27** [comment]
> 

I'm getting the same issue too

**Comment by taz29** [comment]
Having the same issue as well

**Comment by mdorton** [comment]
Same with me - thanks for looking at this when you have time.

**Comment by eugenekotlar** [comment]
Same here.  I downloaded and installed version 2.0.1, and it is still roughing this error.  
<img width="448" alt="2022-09-19_16-05-16" src="https://user-images.githubusercontent.com/48483622/191136540-df85bffd-76b0-4a04-b97a-4405435ef8fb.png">

**Comment by brismuth** [comment]
This type of issue typically occurs when Google is changing their code. The extension will need to be updated to support their new code, but they roll it out in phases to different users, so I will not be able to fix it until the issue occurs for me (and it is not right now).

In the past, impacted users have filed a pull request with the fix - you can see this for an example:
https://github.com/brismuth/google-voice-bulk-texter/pull/82/files

Here's another example of what the fix could look like: https://github.com/brismuth/google-voice-bulk-texter/pull/172/files

**Comment by brismuth** [comment]
Also, I'm guessing that this is caused by the same changes that caused #186, and that Google is just testing it on different users now.

**Comment by MMccombe2022** [comment]
Same Issues or us.  Please post a fix!

**Comment by skiminnetonka** [comment]
Just a quick note this only happens for people in your contact list, I confirmed by deleting and the send worked.

**Comment by Efficiency-super** [comment]
> Just a quick note this only happens for people in your contact list, I confirmed by deleting and the send worked.

Good to know but I can't remove the contact list because those are the people I am sending to. Are you suggesting to temporarily clean the contact and reimport after sending?

**Comment by skiminnetonka** [comment]
Yes that is what worked for me - make the bulk list, delete, send, reimport

**Comment by besariong** [comment]
Quick fix suggestion:

Google probably changed the html and confirmChatSwitched if failing to validate.
recipientButton.innerText does not just contain phone number but mixed label.
Quick workaround was to disable validation entirely and that solved the problem.
confirmChatSwitched() {	return true;}
So,this is how RecepientButton looks like for me:
<gmat-input-chip role="option" gv-id="chip-phone-number" gv-test-id="chip-phone-number" class="mat-chip gmat-chip mat-focus-indicator mat-menu-trigger 
gmat-body-2 grey-700 mat-primary gmat-input-chip mat-chip-with-trailing-icon ng-star-inserted" 
aria-label="Beso G 4 2 4 X X 1 X X X X mobile. Press backspace to remove." tabindex="-1" aria-disabled="false" aria-haspopup="menu">

**Comment by brismuth** [comment]
Thanks so much for that info @besariong!! With that HTML you pasted, I should hopefully have enough context to fix this for everyone.

I just uploaded v2.0.3 - can everyone on here give that a try and let me know if it resolves this issue?

@besariong @skiminnetonka @Efficiency-super @eugenekotlar @mdorton @MMccombe2022 @taz29 @sculley27 @2021msw

**Comment by Efficiency-super** [comment]
> Thanks so much for that info @besariong!! With that HTML you pasted, I should hopefully have enough context to fix this for everyone.
> 
> I just uploaded v2.0.3 - can everyone on here give that a try and let me know if it resolves this issue?
> 
> @besariong @skiminnetonka @Efficiency-super @eugenekotlar @mdorton @MMccombe2022 @taz29 @sculley27 @2021msw

Hi @brismuth Where can I download the file?

**Comment by besariong** [comment]
Did not work for me. Problem is not in selector (selectors.gvRecipientButton) iteslf, gmat-input-chip just does not contain phone number in any structural way (in my version), so would be impractical to extract it for comparison. 
So, I have just short circuited  confirmChatSwitched() { return true; }

**Comment by brismuth** [comment]
Okay, everyone else can hold off on trying v2.0.3. Based on what @besariong is saying, the change I put in won't help.

@besariong does the phone number show up anywhere else in the HTML with the new Google Voice changes?
The reason I have the validation there is to ensure the extension never accidentally sends a message to a previous thread before it's had the chance to change threads. I'd like to keep it in place if possible.

**Comment by besariong** [comment]
@brismuth Number is there, but not in structural way.
see inside my gmat-input-chip (see in my previous comment)
aria-label="Beso G 4 2 4 X X X X X X X mobile.
so, "aria-label" contains first name space last name initial space and  phone number with spaces between numbers.
That's, the only place number is present and not sure how safe it is to rely on that structure.

**Comment by besariong** [comment]
suggested solution:
	confirmChatSwitched() {
		const numberToSend = this.currentNumberSending;
		const recipientButton = document.querySelector(selectors.gvRecipientButton);
		if (recipientButton && recipientButton.offsetParent !== null) {
			const label = recipientButton.getAttribute('aria-label');
			if (label && label.replaceAll(' ','').indexOf(numberToSend) >=0)
				return true;
		}
		return false;
	}

**Comment by brismuth** [comment]
@besariong I love it, that seems like a fairly simple way to handle it, assuming it's always in that format. And, as an added bonus, it looks like your code works fine on the old version of the Google Voice site as well, which is what I have! 

I've pushed out this change with version 2.0.5. 

For folks who installed the extension manually in Chrome, you can follow these instructions to update it:
https://github.com/brismuth/google-voice-bulk-texter#update-it

For those who are using FireFox or Microsoft Edge, 2.0.5 should update onto your computers soon.

Let me know if any of you are still having the issue after updating, or if this resolves it for you!

**Comment by Efficiency-super** [comment]
New release works! Thanks for fixing the issue.

**Comment by brismuth** [comment]
Awesome! Glad to hear it. Thanks again for the help @besariong, great work!!

**Comment by besariong** [comment]
Great! Glad to be able to help.
