### ISSUE TITLE
Bulk texter will only send 2 texts & then refresh - delay in receiving messages

### ISSUE THREAD

**Issue by Mccarty0401** [brismuth/google-voice-bulk-texter#197]
**Describe the bug**
Bulk texter will only send 2 texts & then refresh
Contacted my network administer - they could not fix it - assigned me a new number but still does not work.  Also messages are not coming thru on my computer for a few minutes but are coming thru on my phone

Image attached where you can see I received a text on the left but when I open it I can not read it because it does not show up.

![google](https://user-images.githubusercontent.com/112655118/192160921-b84ee70e-887e-4262-b8a4-7e59a8bbbd1f.jpg)

**Comment by brismuth** [comment]
@Mccarty0401 I only built the chrome extension, I don’t have any control over Google Voice at all. 

It sounds like your issues have to do with Google Voice, and not with the extension, so I won’t be able to help out unfortunately.

**Comment by Mccarty0401** [comment]
The bulk texter will only send 2 messages & then refresh my page

**Comment by brismuth** [comment]
Since it sounds like you’re having a lot of issues with Google Voice that are unrelated to the extension, I’m guessing those are the root cause of the page refresh issue. 

Once you get Google Voice working reliably, if you’re still having issues with the extension, go ahead and post back here.

**Comment by Mccarty0401** [comment]
FYI - After a ton of research , I discovered my computer time was not synced properly .   Your extension worked again after syncing the time.  I really appreciate you creating this app - it make my job so much easier ! (teacher)

**Comment by brismuth** [comment]
I'm glad to hear that! Thanks for the follow up!
