### ISSUE TITLE
Message Keeps Looping

### ISSUE THREAD

**Issue by samricher7** [brismuth/google-voice-bulk-texter#198]
**Describe the bug**
The Message Keeps Looping seeming as it's trying to send. It fails and Sends an error message.
**URL**
The URL you were on when the problem occurred. 
https://voice.google.com/u/0/messages?itemId=draft-C2072650-60CA-4C13-A355-814BE629DA42
**Expected behavior**

**Screenshots**
Google Voice bulk texter v1.3.2:
Text failed. You can find support resources by opening the Google Voice Bulk Texter popup and clicking "Get Help" at the bottom.

Error: "confirmChatSwitched" failed. 

When you click "ok" the page will refresh.
**Additional context**

**Comment by brismuth** [comment]
@samricher7 this issue has already been fixed in the current version of the extension, please update following this guide:
https://github.com/brismuth/google-voice-bulk-texter#update-it
