### ISSUE TITLE
Extension is looping on a single number and failing with an error message

### ISSUE THREAD

**Issue by Jaccooley** [brismuth/google-voice-bulk-texter#199]
**Describe the bug**
The extension is looping on a single number and failing with an error message. 

**URL**
googlevoice.com

**Expected behavior**
send texts to all numbers listed 

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
@Jaccooley this report doesn't not have enough info to help you, please 
1. Update to the latest version of the extension
2. If necessary, file a new issue with a screenshot of the error and what the error message is.
