### ISSUE TITLE
Google Voice just suspended my account - Is this happening to other users? 

### ISSUE THREAD

**Issue by aberryt** [brismuth/google-voice-bulk-texter#20]
I was using google voice and then google kicked me out and suspended my account. I wrote into google saying the suspension was a mistake and cited what I was using at the time it kicked me out. Wondering if other users have reported a similar issue? 

**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
This is the first I've heard of that occurring. That said, Google voice is not intended for spamming or marketing, so if they thought you were doing that, that might be why they closed your account.

**Comment by aberryt** [comment]
hmm ok .. we were updating a party invite list with time and date for the
event.. but it was a big invite so maybe they thought that. Hopefully they
can give us access back. Thanks for your reply.

**Comment by brismuth** [comment]
Please keep me updated with what Google tells you, if you don't mind. Sorry to hear about the inconvenience.

If you don't mind sharing, how many messages were you trying to send out? Might be useful to share with the other users.

**Comment by aberryt** [comment]
No worries and I will. For reference I was trying to send out ~120 texts .
I probably texted this list about once a week for the last month.

**Comment by brismuth** [comment]
@aberryt any luck? Did you end up getting your account access restored?

**Comment by brismuth** [comment]
Closing this issue since I haven't heard back, and since there is now additional information on this topic in the support doc:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md
