### ISSUE TITLE
I keep getting this error: "confirm chat switched failed"

### ISSUE THREAD

**Issue by liroberts** [brismuth/google-voice-bulk-texter#200]

**Comment by chemicalchaos** [comment]
I have been getting the same error - I believe it ONLY HAPPENS when sending to phonenumbers that are in my contacts (i.e., there's a name associated with the number).  Unknown numbers, even if previously texted, appear to be going through.

**Comment by brismuth** [comment]
This is already resolved in the latest version of the extension, you’ll just need to update it:
https://github.com/brismuth/google-voice-bulk-texter#update-it
