### ISSUE TITLE
Issues sending texts using bulk texter 

### ISSUE THREAD

**Issue by Mccarty0401** [brismuth/google-voice-bulk-texter#206]
I have used bulk texter for a few years but this week -Using bulk texter I can sent 1 or 2 messages - then it starts putting multilple numbers in the sending section & then I get a ConfirmChatSwitched error
![image](https://user-images.githubusercontent.com/112655118/202777587-db5fcb11-828c-40f0-b0a4-31ca48198af2.png)
![image](https://user-images.githubusercontent.com/112655118/202777645-63796672-4a7b-4fb6-b30e-9f0857359036.png)

**Comment by brismuth** [comment]
@Mccarty0401 interesting - it looks like it was adding the contact multiple times! This may be the key to resolving #201 as well, not sure.

I've just released a new version to Firefox that should fix this - v2.0.8. I recommend switching to using the Firefox extension, as it will automatically stay up to date.

You can install it here:
https://addons.mozilla.org/en-US/firefox/addon/bulk-texter/
