### ISSUE TITLE
Google terms 

### ISSUE THREAD

**Issue by saborucci** [brismuth/google-voice-bulk-texter#27]
I've read that google voice monitors for commercial use and if I send too many of the same message I will be flagged and potentially blocked from further use. Has this happened to anyone and what are the best practices to prevent this from happening?

**Comment by brismuth** [comment]
The only report of this I've heard is in #20. I'm not aware of any compiled best practices for avoiding being flagged and blocked, but you can see Google Voice's terms of service here:
https://www.google.com/intl/en_US/googlevoice/legal-notices.html

I'll follow up on #20 to see what the end result was.
