### ISSUE TITLE
TextNow

### ISSUE THREAD

**Issue by Qxboxone** [brismuth/google-voice-bulk-texter#32]
Is it possible for you to recreate this same exact thing with https://www.textnow.com/wireless they seem to function similar and I would be highly interested. The problem I'm facing with google voice is it is stopping and not allowing me to send I imagine it is some kind of spam protection. I'm trying to send out a large amount of text without paying 100s of dollars your chrome extension is the closest I've got to that. Let me know what you think and if it can be done.

**Comment by brismuth** [comment]
That would be possible but you'd have to find someone willing to do it. 

This project's source code is MIT licensed, so you're welcome to copy it and reuse it for the other extension that you're wanting to be built.

**Comment by brismuth** [comment]
@Qxboxone we are actually going to build that into Bulk Texter Pro. 

We’ll likely be inviting users to beta test a TextNow integration in the next 4-6 weeks. If you’d like to be part of that beta test, you can reach out to support@bulktexterpro.com.
