### ISSUE TITLE
ERROR "confirmSent" failed

### ISSUE THREAD

**Issue by justamor** [brismuth/google-voice-bulk-texter#34]
**Describe the bug**
The bulk texter sends the first message in the list - then it tries to send the second several times then times out.

<img width="441" alt="screen shot 2019-01-26 at 10 10 01 am" src="https://user-images.githubusercontent.com/47061630/51790089-7bd56f00-2156-11e9-8d17-858354ff6de4.png">

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**
That it works
<img width="441" alt="screen shot 2019-01-26 at 10 10 01 am" src="https://user-images.githubusercontent.com/47061630/51790083-72e49d80-2156-11e9-8695-d888d0146b24.png">

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Did you have the chance to read the tips on the support page? One of them talks specifically about this error.

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md
