### ISSUE TITLE
Went through all the trouble shooting, No luck. The app keeps inputting the previous sent message in the new texts field.  

### ISSUE THREAD

**Issue by justamor** [brismuth/google-voice-bulk-texter#35]
**Describe the bug**
I cannot send on any of my 5 accounts, never happened before. 
It tries to send the same number over and over, Manually I can send just fine.

**Comment by brismuth** [comment]
Does it still happen if you send to one of your own numbers and you use a simple, short message?

**Comment by justamor** [comment]
Oh ok maybe my message was too long

**Comment by justamor** [comment]
its works now, please close my ticket! Thank you for your add on!
