### ISSUE TITLE
I DOWNLOADED THE APP TO MY CHROME BUT IT WONT TAKE ME TO WHERE I CAN TEXT 

### ISSUE THREAD

**Issue by HOLRARCLEF** [brismuth/google-voice-bulk-texter#36]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by HOLRARCLEF** [comment]
I INSTALLED THE BULK TEXTER APP TO MY CCHROME THEN I LOGGED IN MY GOOGLE VOICE NORMALLY. BUT ITS KEEP NOT TAKING ME TO THE AREA WHERE I PUT THOSE NUMBERS I WILL TEXT

**Comment by brismuth** [comment]
After installing the extension at this URL (https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka), you will need to go to https://voice.google.com.

Then you’ll click on the extension’s icon next to your chrome search bar. That will bring up the extension’s bulk texting interface. The interface gives you some examples for how to write messages and put in contact information.

Good luck!

**Comment by HOLRARCLEF** [comment]
![1e0455f5-811a-4dc9-b314-52ab77648782](https://user-images.githubusercontent.com/47066727/51819172-5182cf00-2286-11e9-99f8-2d4b4baad199.jpeg)
![705e6c93-8622-4a9e-a095-8912d00ed115](https://user-images.githubusercontent.com/47066727/51819173-5182cf00-2286-11e9-9a7d-619d222e54b7.jpeg)
i have done as you have instructed but example of what am saying is what i have attached to you here , iw ont just show me the texting sample

**Comment by brismuth** [comment]
Thanks for the screenshots, those are helpful. Looks like your user interface is partially in Portuguese (the search bar says "pesquisar"). The app only supports English right now because it has to actually search for words on the page to click on things and enter text.

I'd guess that's what's causing the issue.
