### ISSUE TITLE
Google Voice Bulk Texter failed because of potential spam?

### ISSUE THREAD

**Issue by fitzgeraldsllc812** [brismuth/google-voice-bulk-texter#38]
I am in contact with many realtors, and need to send them texts/emails monthly.  I just downloaded google voice in an effort to make this easier, but after 13 messages sent at texts to the realtors phones, it failed because of potential spam.  Is there a way to get around this???

**Comment by brismuth** [comment]
I added some additional content to the support page. Beyond that there’s not anything I can do, as this is Google flagging your messages, and not my extension. 
Good luck!

https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md
