### ISSUE TITLE
Bulk Texter is not picking up voice.google.com 

### ISSUE THREAD

**Issue by CLwatches** [brismuth/google-voice-bulk-texter#39]
**Describe the bug**
Recently saw that voice.google.com updated and since then one of my employees keeps getting the error that the bulk texter is unable to find google voice, my other employees aren't having that issue and I notice the google voice looks a bit different on the one where the bulk texter extension isn't working 

**URL**
https://voice.google.com/u/2/messages 

**Expected behavior**
To be able to insert my message and numbers to te
![david google voice](https://user-images.githubusercontent.com/47866633/53195684-2c168600-35e4-11e9-9820-443e1641dd46.png)
![mike google voice](https://user-images.githubusercontent.com/47866633/53195686-2caf1c80-35e4-11e9-85ba-b80e5686e672.png)

xt

**Additional context**

**Comment by brismuth** [comment]
Thanks for filing this issue. I just checked Google Voice on my end and I'm not seeing those new changes to the interface. It seems likely that Google is doing a staggered rollout to people over time. I unfortunately won't be able to update the extension to be compatible until I have the changes showing up on my end.

**Comment by brismuth** [comment]
I updated the support doc to redirect users to this thread for additional comments and to subscribe for updates:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md

**Comment by adefilip** [comment]
I actually was going to post the same message. I have the same issue in my company. When will you know when the google voice update is complete, so you can update this extension?

**Comment by brismuth** [comment]
Unfortunately I don't have any control over when Google switches my account over to the new interface. 🙂
Once it does I'll be able to update the extension though and I'll be sure to post an update on here.

**Comment by timetzel** [comment]
Google switched for me during a text send out this morning. Hope you will be able to be able to update this amazing add on. Thanks!

**Comment by adefilip** [comment]
any updates in general? I am giving a presentation and sharing your amazing add on tomorrow

**Comment by brismuth** [comment]
Looks like the interface just updated for my account today. I'll do what I can to update it today.

**Comment by jodyheath** [comment]
Same here, my interface just updated and I'm out of commission.  I always use it with google voice.  Also tried with hangouts... but to no avail. Thanks for working on the update. Looking forward to it!

**Comment by susyq13** [comment]
Is the update taking place?

**Comment by brismuth** [comment]
@susyq13 haven't done anything to update it yet, I've been at work all day. This extension doesn't exactly pay the bills for me. 😉

I'm hopeful that I'll have some time to get to it tonight though.

**Comment by susyq13** [comment]
Sorry.. did not mean to assume that. I was not sure how this update worked.

**Comment by brismuth** [comment]
I'll need to manually update the extension code to support the new Google Voice interface. Depending on what all changed, the could be anywhere from trivial to a significant pain in the neck. If it ends up being more than I can get to tonight I'll be sure to update on here.

**Comment by brismuth** [comment]
I've just pushed the update to handle the Google Voice redesign to the Chrome Web Store (the extension is now v1.1.0). It can take up to 60 minutes to become available there, and it can take longer than that to actually show up on your computer unless you force it to update. 

Once you see 1.1.0 available at this link (https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka), you can force Chrome to update the extension by simply uninstalling and reinstalling it.

**Comment by brismuth** [comment]
FYI ^ @CLwatches @adefilip @timetzel @jodyheath @susyq13 @shannonmullaney

**Comment by adefilip** [comment]
I have the new google voice update today and the new extension update you did. Both worked for me. Thank you!

**Comment by KLefk** [comment]
Thank You!
I uninstalled, reinstalled, refreshed google voice, back in business. SO appreciate this extension - yes, will donate.

**Comment by susyq13** [comment]
Thanks so much.

**Comment by CLwatches** [comment]
My staff and I thank you for the update and the hard work you did with getting this out so quickly. @brismuth
