### ISSUE TITLE
copy and paste from keyboard

### ISSUE THREAD

**Issue by adefilip** [brismuth/google-voice-bulk-texter#42]
**Describe the bug**
I am just checking.....I cannot use the copy and paste function from my keyboard while the extension is texting. (it just pastes the message into my other work). Is this correct or a new issue since the update?

Thank you for any information you can provide.

**Comment by brismuth** [comment]
That's correct. Google Voice has code in place that prevents regular javascript from writing the text messages, so the extension has to use Chrome's copy/paste APIs (only available to extensions) instead. That was the case before the update as well.

Sorry about that!
