### ISSUE TITLE
SELECTION OF GV

### ISSUE THREAD

**Issue by Dennis860** [brismuth/google-voice-bulk-texter#43]
I have like 4 google voice acts..to my suprise like 2 worked with bulk texter while another 2 didn't work . Plese have u heard about this problem/issue before where some work and some wouldn't. Just wanna know if it selects. Please advise

Thanks

**Comment by brismuth** [comment]
What version of the extension are you on?

**Comment by Dennis860** [comment]
v1.1.0

**Comment by brismuth** [comment]
Can you describe what is happening on the accounts for which it isn't working? Screenshots would be helpful too if possible.

**Comment by Dennis860** [comment]
![google voice](https://user-images.githubusercontent.com/47046943/53692830-d76acc00-3d96-11e9-8911-c7ac7b5fee04.png)
![hangout](https://user-images.githubusercontent.com/47046943/53692832-e05b9d80-3d96-11e9-826c-6e6c0433812a.png)
![good google voice](https://user-images.githubusercontent.com/47046943/53692851-16008680-3d97-11e9-8597-b3739bdaaf5f.png)


I attached 3 screenshots....the google voice interface of an account working well with the bulk texter, google voice interface of an account that is not working and its hangout interface showing prepare message.

**Comment by Dennis860** [comment]
I can as well share login details for those accounts with you so you can look into it and see what actually happened. So you can update me on how to overcome such problem

**Comment by brismuth** [comment]
The extension only supports the interface in the English language. You'll need to change the accounts that are in Spanish to English.

**Comment by Dennis860** [comment]
Thanks and it is fixed...Thanks a lot
