### ISSUE TITLE
{name} suggestion

### ISSUE THREAD

**Issue by adefilip** [brismuth/google-voice-bulk-texter#44]
**Additional context**
This is just a suggestion. But could there be a way to include the {name} in other places in the message besides the greeting? This way you could include the persons name more than once. Thank you.

**Comment by brismuth** [comment]
Yes, that can be done. I'll update this thread when I get the chance to add support for that.

**Comment by adefilip** [comment]
Follow up question....what are the chances about being able to include an image?

**Comment by brismuth** [comment]
No, that won't be possible as far as I can tell. If Google Voice supported images pasted from the clipboard that would make it a little easier, but they make you go through the google photos modal right now. 

If someone else wants to look into implementing that feature I'd be open to a pull request.

**Comment by brismuth** [comment]
Your suggestion for improving the `{name}` functionality is rolling out now with v1.1.1. Thanks for suggesting that!

**Comment by vpaul19** [comment]
Hi first, THANK YOU for this extension it's amazing.  Is there a way to add a custom {__} function.  Say...{name} at {address} and so forth?  That would be awesome.  Thanks

**Comment by brismuth** [comment]
@vpaul19 that request is a duplicate of #49. You should subscribe to or comment on that one.
