### ISSUE TITLE
does the support html...Can I send html as sms through this your extension. or does GV allows this

### ISSUE THREAD

**Issue by Dennis860** [brismuth/google-voice-bulk-texter#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brismuth** [comment]
You can always give it a try and let us know! 

I'd guess it will send HTML as HTML, but no one's texting client is going to render it. It will just show up as HTML.
