### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by james-halpert** [brismuth/google-voice-bulk-texter#46]
**Describe the bug**
We can type a message and enter all the phone numbers. When "Send Messages" is clicked, the extension simply closes

**URL**
https://voice.google.com/u/0/messages

**Expected behavior**
We expected the extension to begin bulk texting one phone number at a time

**Screenshots**

**Additional context**
I found that if I only entered 30 contacts the messages sent.

**Comment by brismuth** [comment]
Can you confirm the version you're on?
Also, can you try the later contacts in the list without the first 30 to make sure it's not an issue with a specific contact?
How many contacts are you trying to insert when it's crashing?

**Comment by james-halpert** [comment]
I’m on version 1.1
I have tried them in different orders and it doesn’t make a difference. I
was able to send out all of the texts but I had to break it into three
delivery groups. The first group was 30. The 2nd group was 60, but had an
error partway through (sending again to the error number was successful).
The 3rd group was 60 people again with 1 error. If I try more than 60 at a
time it will crash without an error.

**Comment by brismuth** [comment]
Do you mean version 1.1.1 or 1.1.0?

**Comment by james-halpert** [comment]
1.1.1

**Comment by brismuth** [comment]
What is the error that you said is occurring partway through?

**Comment by james-halpert** [comment]
The generic send error we’ve always received on occasional numbers. Sorry I
don’t have the exact text.

**Comment by brismuth** [comment]
Ok, to clarify, you're not concerned about the error that's happening with the group of 60, or at least it's not new.
You're just reporting that there's a new error happening when you try to put contact info in for all 150 at once. Is that right?

**Comment by james-halpert** [comment]
That’s correct

**Comment by brismuth** [comment]
Do you get any message when it crashes or does the pop-up just disappear?

**Comment by james-halpert** [comment]
The window for the extension closes and it returns to the google voice
screen

**Comment by brismuth** [comment]
I think I've tracked it down to this issue:
https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot

There's a character limit of 8,192 characters for saving the names and numbers to Chrome Synced storage, which I switched to with v1.1.1. To resolve this I've moved it back to local storage for v1.1.2. 

Once you get v1.1.2, let me know if you're still experiencing the issue and I'll look into it some more.

**Comment by james-halpert** [comment]
Will do, thanks very much

**Comment by brismuth** [comment]
@james-halpert did this fix your issue?

**Comment by james-halpert** [comment]
I’m out of the office today but I will know by Monday morning and let you
know

**Comment by james-halpert** [comment]
Hi, the issue still remains. We show version 1.1.2. But we still have send
messages in groups at a time. Sending with all numbers in the list results
in the extension closing.

**Comment by brismuth** [comment]
Is there any way you could record a video of the issue occurring? I haven't been able to reproduce the issue on my end.

**Comment by james-halpert** [comment]
vokoscreen-2019-03-14_07-43-40.mkv
<https://drive.google.com/file/d/1mQxXqZfZBsPLkuueShzSo_0rDj7ZFP1r/view?usp=drive_web>
Here is a capture I made last week on Thursday (v. 1.1.1) but the same
result occurs now with v.1.1.2

**Comment by brismuth** [comment]
Thanks for the video. I've tried a few times but have been unable to reproduce the issue on my side.

Would you be able to experiment and track down the exact number of line items and the character count at which it starts failing?

**Comment by james-halpert** [comment]
Absolutely. I’m out of the country currently but when I return on the 1st I
will let know the results.

**Comment by james-halpert** [comment]
Everything worked yesterday, but today it appears google updated the UI on
google voice and now we are unable to send anything to even a single user.

**Comment by brismuth** [comment]
@james-halpert see issue #48. Thanks for reporting.

**Comment by brismuth** [comment]
The fix to the last issue you mentioned is now resolved.

I still haven't had any luck reproducing your issue where it crashes if you put in too many numbers.

**Comment by james-halpert** [comment]
Everything looks good for us on this end. You can consider our issue
resolved. Thank you for your work.
