### ISSUE TITLE
Google Voice Bulk Text NOT Sending Multiple #'s

### ISSUE THREAD

**Issue by JRuby14** [brismuth/google-voice-bulk-texter#51]
I have been using this for 2 weeks with NO issues. Today, I tried using it and it attempts to send, shows the message and number, pauses and never sends. Then it repeats trying to send to the same number again and just repeats WITHOUT sending. I would normally input 20 numbers and they would get sent without pause.  Although I did notice that I had to have Google Voice open and showing on my screen for it to work, any work around on that as well?  Please advise on how I can fix. Thanks

**Comment by brismuth** [comment]
@JRuby14 see issue #48.
