### ISSUE TITLE
Tool Stopped Working

### ISSUE THREAD

**Issue by ryanrohypnol** [brismuth/google-voice-bulk-texter#56]
The tool inputs the number & message correctly but fails to submit the messages. Just a heads up.

**Comment by jodyheath** [comment]
I've been getting this error message since Sunday 3/31

![image](https://user-images.githubusercontent.com/48029104/55586626-4e6cea80-56de-11e9-8f8c-c410cbd4c647.png)

**Comment by brismuth** [comment]
See issue #48.
