### ISSUE TITLE
Not sending messages

### ISSUE THREAD

**Issue by nobscryptochris** [brismuth/google-voice-bulk-texter#59]
**Describe the bug**
I've used this with success in the past, but now it is showing the screenshot error below after not sending messages. Love the app. Thanks!

![image](https://user-images.githubusercontent.com/44205954/55654299-9f501200-57b6-11e9-83c5-47524f9b7008.png)

**Comment by brismuth** [comment]
Bizarre. That isn't the latest version of the extension (v1.1.3 is out now), but that isn't an issue I'd heard of anyone else reporting. Can you try force-updating the extension by uninstalling it and reinstalling it and see if that resolves it for you?

**Comment by Alyssa717** [comment]
My messages also stopped sending. It sent like the first 15 and then it just stopped. I got the following error message. 
![Screen Shot 2019-04-11 at 09 50 36](https://user-images.githubusercontent.com/49525549/55962813-9db39d80-5c3f-11e9-9d4d-bfeb12f6879c.png)

**Comment by brismuth** [comment]
This is a known and documented issue caused by Google Voice flagging your messages as spam. See the support doc:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/support.md
