### ISSUE TITLE
sending text issue in the background

### ISSUE THREAD

**Issue by adefilip** [brismuth/google-voice-bulk-texter#60]
**Describe the bug**
had to keep the tab up and open when sending bulk text. 

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**
When I previously sent bulk texts by the extension, I could open a second tab for google text and reply to texts or work on other tasks. This week if I left the google voice tab, the bulk texting extension would stop sending texts. Is this a new feature or is there an issue?

**Comment by brismuth** [comment]
The last change to the extension was almost 3 weeks ago. 

As far as the functionality you're describing, I've never personally tried using the extension with the Google Voice tab in the background. If it suddenly stopped working that way, I'd guess Google changed something in either Chrome or the Google Voice application, and there's probably not much I can do to change that.
