### ISSUE TITLE
Bug: Bulk texter only sends a single message if the message contains emojis

### ISSUE THREAD

**Issue by MariaVzla** [brismuth/google-voice-bulk-texter#61]
**Describe the bug**
The bulk text will not send because I keep receiving an error message of fileNumberInput

**Expected behavior**
I expected to have the bulk text successfully send

**Screenshots**
![Screen Shot 2019-04-23 at 5 16 27 PM](https://user-images.githubusercontent.com/49920772/56619565-956a4380-65eb-11e9-903f-9a6bb73fee59.png)

**Comment by brismuth** [comment]
Was it working for you before?

Can you try sending it to your own number and see if that works?

**Comment by MariaVzla** [comment]
Hi there,

Yes it was working before. I just tried sending it to my own phone number
and I get the same error message.

**Comment by adefilip** [comment]
Has this been resolved?

**Comment by brismuth** [comment]
I haven't been able to reproduce this issue at all, and it looks like it's working for most people. If someone can get me steps to reproduce I can look into it.

**Comment by adefilip** [comment]
My co-work may have figured it out. She had an emoji in her text. Once she took that out the extension worked again

**Comment by brismuth** [comment]
@gmt @MariaVzla @adefilip this issue is resolved and emoji support is added in version 1.2.0. 
If you are affected by #102 or #111, those are not resolved yet.
