### ISSUE TITLE
I have a long string of number to send out messages to, but it keeps stopping part way down the list

### ISSUE THREAD

**Issue by Jaydsadler** [brismuth/google-voice-bulk-texter#7]
**Describe the bug**
protocol seems to have issues with certain phone numbers

**URL**
google voice

**Expected behavior**
If it is a bag number or a number that doesn't support text I would expect maybe a failure notification, but not an end to the protocol

**Screenshots**
![image](https://user-images.githubusercontent.com/43420669/45774833-4a2e2380-bc0b-11e8-9f37-686e594f8448.png)

Not sure if the screenshot worked, but it says if I'm using hangouts I might need to change it so that it's not handling sms.

**Additional context**
I did some tests with about 5 numbers, but when I added the whole list of about 100 numbers now it seems like it can't ever get through more than about 5 of them.

**Comment by brismuth** [comment]
Thanks for reporting this issue! I've received a couple other reports of this issue but haven't been able to reproduce the behavior on my end, which has made fixing it difficult. Your screenshot is super helpful. 

Questions:
1. Have you noticed any pattern in the numbers failing? Are they US phone numbers? Are they all contacts that are saved in your account?
2. If you change the order of the numbers, does it still fail after ~5 of them?

**Comment by Jaydsadler** [comment]
I haven’t played with it too much as I didn’t want to annoy people with a bunch of texts. I’m not completely sure who is and isn’t getting the texts though I figure if it doesn’t show up on my google voice account they most likely didn’t receive anything. I’m certain that some of the number I have are old and no longer in use, or don’t accept texts which I think is the most likely explanation, but I do have another google voice account that I do use sms through hangouts with, and I thought it might be possible that it’s somehow causing the issue. I did erase the top few numbers on the list to see if it’d continue, and it had a similar error. All of the contacts should be on my contacts list though there could be some that aren’t, and they are all US numbers. I may try sending the message to each number individually to see if I get the error on just certain numbers.

Hope that helps. I’m assuming this does work with very long lists typically without issues?

Thanks

**Comment by brismuth** [comment]
Thanks for the additional context. Your understanding should be correct - if your google voice account doesn't show an outbound message, the person shouldn't have received anything either. To answer your question, I typically use it to send to lists of 60-100 contacts and have never had any issues with it.

Another question - when it hangs like that, is the number in the `To:` field or is that field empty? (See number in `To:` field in the screenshot:
![image](https://user-images.githubusercontent.com/5679695/45780131-1d353d00-bc1a-11e8-949d-18921b7da988.png)

**Comment by Jaydsadler** [comment]
Just now I thought I’d try sending one text through the app to one person and it somehow sent it to someone else that was in my list previously, but not to who was listed and it sent the text 5 times again

**Comment by Jaydsadler** [comment]
Tried one more time to just send a text to two of my own phone numbers and neither one received the message and it randomly scanned through a bunch of numbers and picked someone from my list of contacts and sent them the text. Apparently it isn’t even pulling the number to text from the phone number box. Also it sent the text 6 times this time around.

**Comment by Jaydsadler** [comment]
Okay so this might help, whatever happened seems to have partially crashed google voice. When I went to create a text message with google voice not using the chrome app it wouldn’t allow me to send any messages and I had to reopen the tab. I say partially crashed because the texts that did go out still showed up in my feed. When I initially tested this I only used numbers is it possible that adding names caused this to be an issue? I tried with just my two number and it worked fine after reopening. Thanks for your help

**Comment by brismuth** [comment]
Did you refresh the page between those attempts? I'd guess that if that error popup shows up and you keep using the extension without refreshing it would get into a weird state, which is why it would send to people that were previously on your list, and send messages multiple times. 

I think I can probably trigger a refresh automatically when that error message is closed, which would prevent that from happening again. It's almost certainly a side effect from that initial failure though.

**Comment by brismuth** [comment]
Thanks so much for your patience and your help improving the extension. 

For now, if you get that error make sure you refresh the page before using the extension again. Tonight I'll add functionality to autorefresh after an error like that.

**Comment by Jaydsadler** [comment]
I thought I'd test it out with a bunch of spam numbers in my phone. It 
got to the third number and just stopped. No error this time and it was 
right after opening google voice


The error does come up if I try to do anything after it freezes on me.

Sorry for bothering you so much, but this app would be super helpful for 
me. Also I realized that I wasn't putting the format the same as how you 
have in the example, but tried again with the change and got basically 
the same thing but got one number further down the list.
Thanks again.

------ Original Message ------

**Comment by brismuth** [comment]
No worries, I'd really love to get this issue fixed too if I can track it down. Can you send me a full screenshot of the error that happens along with the background?

I'm mainly wondering if when it hangs like that, if the number is in the `To:` field or if that field empty. (See number in `To:` field in the screenshot:
![image](https://user-images.githubusercontent.com/5679695/45780131-1d353d00-bc1a-11e8-949d-18921b7da988.png)

**Comment by brismuth** [comment]
@Jaydsadler I've just rolled out some changes that _may_ resolve the issue 🤞🤞. Again, I've never been able to reproduce the issue locally, so it's a bit of a shot in the dark. 

You can manually get the latest version of the extension by going to chrome://extensions in your browser, toggling the "Developer Mode" to on, and hitting the "Update" button at the top. Once the version for Google Voice Bulk Texter shows 0.3.2, you should be good to refresh your voice.google.com tab and try out the changes. 

Let me know if that fixes the issue, and if it doesn't, please forward me a full screenshot of where it is locked up. Thanks!

**Comment by Jaydsadler** [comment]
Okay so I ran another test it stopped on the 4th number on the list, I erased all but my personal number and sent the message again, it then sent a text to the 6th person on my original list and I never received anything. I didn’t see the error until the second message. The message was duplicated on the second try, but after clicking ok it reset the page.

**Comment by brismuth** [comment]
Thanks for trying that out. So if I understand correctly, after your first usage of the extension today, it started to hang on a page, and then you used the extension again before the error popup could trigger. Is that correct?

Also, please answer this question. When it hangs like that, is the number in the `To:` field or is that field empty? (See number in `To:` field in the screenshot:
![image](https://user-images.githubusercontent.com/5679695/45780131-1d353d00-bc1a-11e8-949d-18921b7da988.png)

**Comment by Jaydsadler** [comment]
The first use just stopped after the forth number. It showed nothing in the  to: field . After that apparently any effort to send a message will create the error popup and hitting okay on that will not trigger a refresh. There is no error when it freezes up after the first few numbers. On a second message it will show the correct number in the to field, but seems to continue to try to message from the first list, at the point where it got hung up.

**Comment by brismuth** [comment]
Would you be willing to record a video of what it's doing now from start to finish? Another user used https://screencast-o-matic.com/ for that before and it worked well. Sorry about the hassle, and thanks for helping me get to the bottom of this.

**Comment by brismuth** [comment]
In version 0.3.3 I've fixed some bugs that would have occurred sometimes. I'm not sure if they're related to the issue you reported or completely separate though. Let me know if you see any change or improvement in the extension on your end.

**Comment by Jaydsadler** [comment]
I tried to send you a video, but it says the file is too large. It’s only 3mbs. Can I send it to a different email?

 

From: Jay Sadler [mailto:Jaydsadler83@gmail.com] 
Sent: Thursday, September 27, 2018 12:10 PM
To: 'brismuth/google-voice-bulk-texter'; 'brismuth/google-voice-bulk-texter'
Cc: 'Mention'
Subject: RE: [brismuth/google-voice-bulk-texter] I have a long string of number to send out messages to, but it keeps stopping part way down the list (#7)

 

Sorry this took so long to get to you. I was hopeful that the update would fix things. Also I thought I should mention that the phone numbers I’m using are stored in a google sheet and are copied and pasted into the app is it possible that that is causing the issue. When I’ve typed several numbers I’ve not had any issues, but I’ve had a much smaller list. Typically the app fails after sending only one text.

**Comment by brismuth** [comment]
Can you try uploading it to Youtube and sharing the URL here?

**Comment by Jaydsadler** [comment]
Here’s a google drive link of the file. That should work.

https://drive.google.com/open?id=1_FM3-uZQhEMR0jEpilKwwA8rta718x82

**Comment by brismuth** [comment]
That works for me. Thanks! I'll review it in the next couple days and see if I can track the issue down.

**Comment by Jaydsadler** [comment]
I just tested it out, and it looks like everything worked the way I’d expect it to. It’ll pause after every few numbers, but continued on after that without any issues.

Thanks

**Comment by brismuth** [comment]
Great! I'm glad to hear it! The reason for the pause is that sometimes the Google Voice application itself (not the extension) takes a while to respond. That's what was causing the crashes previously, so now the extension is waiting until the Google Voice application is finished before moving on. 

You should be good to unshare your video demonstrating the issue now. I noticed you use the extension to send messages to your Elders quorum, that's what I use it for as well. 😄 

If you wouldn't mind leaving the extension a review, I'd appreciate it.
https://chrome.google.com/webstore/detail/google-voice-bulk-texter/gdplkhplnfgmodalfimcondhmokmekka

**Comment by Jaydsadler** [comment]
Yes this has definitely simplified a few things for me.

Thanks
