### ISSUE TITLE
Bulk Texter: some messages not recieved

### ISSUE THREAD

**Issue by sbagwell15** [brismuth/google-voice-bulk-texter#70]
**Describe the bug**
I only have 16 recipients on a bulk text.... some get the text and others don't... there is no error code or any indication of which recipients aren't receiving the message... so I don't know who to resend to

**URL**
https://voice.google.com/u/2/messages?itemId=t.%2B16468066072

**Expected behavior**
I expected the text to go out to all 16 recipients 

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
Assuming that the texts show up as "sent" in your Google Voice interface, the issue you're describing us a Google Voice issue, and not an issue with the extension. There's nothing I can do to help with that.

**Comment by sbagwell15** [comment]
Cool... I just wanted to reach out to you first and then them.  I don’t
know very much about technology so I was going for the low hanging fruit.

Thanks so much for your time.

Sam
