### ISSUE TITLE
message color coding

### ISSUE THREAD

**Issue by jacktgolf** [brismuth/google-voice-bulk-texter#71]
When a message has been appears to be sent, Google Voice display a message in the box below the "make a call" area.... In-bedded in that message is the phone number sent,  the time and a short few words from the message itself.  It also send back a persons profile in a color circle.  It appears that the color of that circle either  matches either the internet carrier that the message was identified with or a error color code.  This has to be in a simple lookup table with the application.  How can we get a copy of that color coding table.  I really do not need the color code for valid message/ internet pairs but I would like the color code for the unidentified messages.  I think I have found one but would like to validate assertion with concurrence from Google Voice.  I am the Sec/Treasurer of a large AA group and want to use Voice to announce when out meeting location changes (for various reason a few times a year,  the church needs to use its meeting hall) and also i am trying to see when number are still valid (this is a anonymous program) so many of our fellowship disappear ,  die ,  go to jail or lost there throw away phones.  I am trying to cut down on the number of needless messages sent.  Any help would be greatly apprenticed,

**Comment by brismuth** [comment]
Google Voice is a service provided by Google, and I have no affiliation with it beyond the chrome extension I built. I have no idea whether Google has any secret color coding based on text deliverability.

I'm also not aware of anyway to be certain an SMS message has been delivered, other than asking the recipient to respond to you and let you know.

Good luck!

**Comment by jacktgolf** [comment]
Thank you Brian, I did not think u had the answe but it was a 'hail mary'
 I try and see if I can get a answer from the google voice folks(if i can
find them) and I let you know if sucessful.  THanks agin
