### ISSUE TITLE
Kicked off

### ISSUE THREAD

**Issue by allielindstrom** [brismuth/google-voice-bulk-texter#73]
I may have written too long of texts and been reported as spam. The extension no longer exists on my browser, and the link to the chrome store is broken/giving me a 404 error. 

Am I kicked off forever? Did I ruin this for others?

For more context, I invited 90 people to a phonebank via text, none of which were in my contacts. I did get the error while texting but was able to restart it.

**Comment by bhasden** [comment]
I believe the extension was removed from the Chrome Web Store altogether. I also don't see it anymore and have had it automatically removed from my browser.

**Comment by ryanrohypnol** [comment]
Just go into your extensions and turn it back on, Chrome disabled it. It's still in your extension list!

**Comment by allielindstrom** [comment]
Ok! It also just popped back up on its own, which is weird. Thanks!

**Comment by bhasden** [comment]
> Just go into your extensions and turn it back on, Chrome disabled it. It's still in your extension list!

Yep. It's listed as "This extension violates the Chrome Web Store policy." in my extensions now and was automatically turned off. I just turned it back on and everything is well. Thanks for the tip.

**Comment by EdWood110** [comment]
Does this mean this extension will disappear soon for good?

**Comment by brismuth** [comment]
The project readme has instructions for installing the extension from source:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it-from-source

That should continue to work regardless of whether or not they permanently remove the extension from the Chrome web store.

**Comment by tschurm** [comment]
Hi - 

Having issues with bulk texter again.  Used the toggle yesterday and tried deleting it and reinstalling with the above source but it is not working again today intermittently.  Some are getting responses in Google Voice Legacy of being locked out and unable to reply to the bulk text sent.  It appears the extension is working in Hangouts to some degree.  Help!

**Comment by brismuth** [comment]
@tschurm it sounds like you're describing a separate issue so you should open a separate issue/thread to track it.

**Comment by brismuth** [comment]
Final update on this - I reached out to Chrome Web Store support staff, and they confirmed that the extension was removed from the store because it violated the Google Voice terms of service. They didn't mention any Chrome Web Store terms it was violating, just the Google Voice terms.

This means that installing from source will continue to be the only way to install and update this extension:
https://github.com/brismuth/google-voice-bulk-texter#install-it
