### ISSUE TITLE
google text

### ISSUE THREAD

**Issue by lfacey** [brismuth/google-voice-bulk-texter#74]
**Describe the bug**
Google text wont allow me to send a text.  
**URL**
https://voice.google.com

**Expected behavior**
sending texts back and forth

**Screenshots**
![image](https://user-images.githubusercontent.com/53103334/61875263-3bae3980-aeb8-11e9-9211-65c14c35d636.png)
![text not sent](https://user-images.githubusercontent.com/53103334/61875300-4ec10980-aeb8-11e9-8a91-f6b59bb39a52.jpg)

**Additional context**

**Comment by brismuth** [comment]
I only maintain the extension. I have no affiliation with or control over the Google Voice service itself.
