### ISSUE TITLE
extension won't work

### ISSUE THREAD

**Issue by melissagaye** [brismuth/google-voice-bulk-texter#79]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**
![Uploading image.png…]()

**Additional context**

**Comment by brismuth** [comment]
You didn't provide much info to go on.

**Comment by brismuth** [comment]
Can you provide any additional information?

**Comment by melissagaye** [comment]
It tries to send and then I get this:
[cid:image001.jpg@01D54622.0AD60C10]

Individual texts to numbers including mine go through. I can copy and paste, I can’t use the bulk texter.
Thanks so much!

Melissa Gaye
SeeLevel HX
Scheduler
215-680-1773 – Cell
859-935-5121 - Google Voice
Melissa.Gaye@seelevelhx.com<mailto:Melissa.Gaye@seelevelhx.com>
www.seelevelhx.com<http://www.seelevelhx.com/>
www.seelevelshoppers.com<http://www.seelevelshoppers.com/>

Driving a Human Experience That Exceeds All Others

**Comment by brismuth** [comment]
You'll need to add your screenshot to GitHub, it doesn't work if you email it.

I'm guessing this is a duplicate ticket of #75 though.

**Comment by brismuth** [comment]
You'll need to manually update the extension following these instructions.
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it

**Comment by melissagaye** [comment]
Thank you!

Thanks so much!

Melissa Gaye
SeeLevel HX
Scheduler
215-680-1773 – Cell
859-935-5121 - Google Voice
Melissa.Gaye@seelevelhx.com<mailto:Melissa.Gaye@seelevelhx.com>
www.seelevelhx.com<http://www.seelevelhx.com/>
www.seelevelshoppers.com<http://www.seelevelshoppers.com/>

Driving a Human Experience That Exceeds All Others
