### ISSUE TITLE
Problem with google voice bulk texter start error

### ISSUE THREAD

**Issue by cadasupportgroup** [brismuth/google-voice-bulk-texter#80]
**Describe the bug**
Error: startchat failed. Once I press send on the bulk texter it tries to send to the first person on the list, but then fails to start. 

**URL**
https://voice.google.com/messages

**Expected behavior**
I expected the messages to start sending out to everyone on my list as usual.

**Comment by smhennes** [comment]
please follow the below - being worked on now.

https://github.com/brismuth/google-voice-bulk-texter/issues/75#issuecomment-516404193

**Comment by brismuth** [comment]
You'll need to manually update the extension following these instructions.
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it
