### ISSUE TITLE
Extension doesn't show up in Google Voice

### ISSUE THREAD

**Issue by jamihaney** [brismuth/google-voice-bulk-texter#84]
**Describe the bug**
I've installed the extension but it doesn't appear in Google Voice

**URL**
https://voice.google.com/messages?itemId=draft-F9554F0A-539E-4869-A55F-D6CE548E0617

![2019-08-06](https://user-images.githubusercontent.com/53838545/62576148-e3851900-b861-11e9-80e3-e0d8049fe505.png)
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by brismuth** [comment]
The extension icon is near the top right of your browser. It's the one with the four message bubbles. You just need to click that.
