### ISSUE TITLE
This extension violates the Chrome Web Store policy

### ISSUE THREAD

**Issue by adefilip** [brismuth/google-voice-bulk-texter#85]
The chrome extension says that the bulk texter "This extension violates the Chrome Web Store policy". Does this mean that your extension no longer works?

![google voice bulk texter](https://user-images.githubusercontent.com/47867915/62587895-d7b14b00-b891-11e9-8ef3-700499b08f52.JPG)

**Comment by brismuth** [comment]
Google removed the extension from the Chrome web store. You can follow these instructions to install the extension from source code:
https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#install-it
