### ISSUE TITLE
Extension looping on a single number or erroring with "startChat" failed

### ISSUE THREAD

**Issue by Jhancock2** [brismuth/google-voice-bulk-texter#87]
**Describe the bug**

**URL**
The URL you were on when the problem occurred. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Jhancock2** [comment]
I've been using this extension for months and worked great!

Now when I go to load a text, it fills in the phone number, but never loads the text or sends!

**Comment by brismuth** [comment]
If you answer some of the questions in the form then there's a chance I'll understand what the issue is that you're trying to report.

**Comment by brismuth** [comment]
Does it just keeps looping on the contact info without adding the text?

**Comment by Jhancock2** [comment]
Describe the bug
Text doesn't load into the text box.

URL
https://voice.google.com/u/0/messages?itemId=draft-F2BD7E35-92C2-44AF-BBBA-B22B6DD71906

Expected behavior
number to auto load, text to auto load, send command atomomatically.

Thank you for the quick reply and a great extension!

**Comment by Jhancock2** [comment]
It loads only the first number, and continues to reload that one number, without moving on to load the text.

**Comment by brismuth** [comment]
Ok, thanks for reporting this. It sounds like Google may be in the process of rolling out some slight UI changes that might be breaking it.

**Comment by Jhancock2** [comment]
voice.google.com says:
Google Voice bulk texter v1.1.4:

Error: "startChat" failed.

This is whats popping up.

**Comment by mandybug** [comment]
Experiencing the same issue here. It started happening after the last Google Voice update.

**Comment by brismuth** [comment]
The other bug reports that I linked to this one also indicate that Google Voice is rolling out some UI updates that are breaking the extension. Once I get the Google Voice updates on my end I can update the extension to work with them. In the meantime, anyone affected by this issue is also welcome to submit a pull request updating the code to work. 

Usually when Google Voice updates their UI, it's just a matter of updating some of the changed selectors in this file: 
https://github.com/brismuth/google-voice-bulk-texter/blob/master/src/contentScripts/main.js

**Comment by brismuth** [comment]
@Jhancock2 @mandybug @CJPenn are you all still experiencing this issue? It still seems to be working fine for me.

**Comment by mandybug** [comment]
@brismuth  - just tried it. Same error.

**Comment by brismuth** [comment]
Can you confirm the version number showing in the pop up?

**Comment by mandybug** [comment]
@brismuth startChat failed #88

**Comment by mandybug** [comment]
![startchat failed](https://user-images.githubusercontent.com/54292641/68606213-970a3480-0473-11ea-9101-cee803e29c24.PNG)

**Comment by palacepe** [comment]
Hello, 
I have the same issue.

**Comment by brismuth** [comment]
@mandybug @palacepe can you update to v1.1.5 following the instructions in the readme? It was released a few months ago and I think it will probably resolve the issue for you.

https://github.com/brismuth/google-voice-bulk-texter/blob/master/README.md#update-it

**Comment by mandybug** [comment]
@brismuth  - like a charm. Oh, how I've missed it. Thank you, thank you!! <3

**Comment by brismuth** [comment]
Sorry I didn’t post back on this thread when the fix was released before - it slipped through the cracks.

Glad it’s working now though!
