### ISSUE TITLE
Last phone number in list is repeated but not sent

### ISSUE THREAD

**Issue by magowemogithub** [brismuth/google-voice-bulk-texter#89]
**Describe the bug**
Enter phone numbers only in the Numbers, names field, enter a message without the custom name in the Message field. Enable the Policy message box, Send Messages.
Problem: the last number in the list is entered again into the To field in Google Voice. The text is not entered again, and the message is not sent.

**URL**
https://voice.google.com

**Expected behavior**
I did not expect another number to be entered into the To Google Voice page after the last number was sent a text message.

**Screenshots**
![brismuth](https://user-images.githubusercontent.com/7862206/63988991-7f85f700-ca93-11e9-9b51-4e9d305cc3cd.jpg)

**Additional context**
N/A

**Comment by brismuth** [comment]
Are you able to reliably reproduce this behavior? I haven't seen it before.

**Comment by magowemogithub** [comment]
Hi Brian,

Yes. Every time.

Thank you,
Sean
