### ISSUE TITLE
Stuck on the first number and receiving error message

### ISSUE THREAD

**Issue by CJPenn** [brismuth/google-voice-bulk-texter#92]
**URL**
https://voice.google.com/u/0/messages?itemId=draft-2E756AF8-C556-44FE-8FBF-315D4E32AABF

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55103949/64552344-13ae5480-d305-11e9-8414-c7146c705279.png)

**Additional context**

**Comment by brismuth** [comment]
Duplicate of #87.
