### ISSUE TITLE
Google voice bulk texting 

### ISSUE THREAD

**Issue by JRARTHUR** [brismuth/google-voice-bulk-texter#95]
I cant load the master zip file to be to use the bulk texter , its saying its missing proper extension

**Comment by JRARTHUR** [comment]
This is my error message


Failed to load extension
File
~/Downloads/google-voice-bulk-texter-master/src/contentScripts
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by brismuth** [comment]
You need to select the src folder, not the contentScripts folder.

**Comment by JRARTHUR** [comment]
I tried that and got same error

**Comment by JRARTHUR** [comment]
I will try again
