### ISSUE TITLE
All messages being sent to all phone numbers

### ISSUE THREAD

**Issue by Ecinele** [brismuth/google-voice-bulk-texter#96]
Hi
I am trying to send out my messages.
Unfortunately, all of my messages are being sent to each phone number on the list.
I followed the instructions and I really need your help.
Thanks
Helenice Chroniger

**Comment by brismuth** [comment]
You're only supposed to write one message, and then that message is sent to each phone number on the list. 
If you're writing multiple messages into the single message input, then it will send the entire thing to each phone number on the list, as expected.

**Comment by Ecinele** [comment]
Is there any way that I can send different messages to different numbers as
a bulk text?
Thanks

**Comment by Ecinele** [comment]
I am a teacher and need to send similar messages but not the same message.  I Know I used your program in the past and it worked.  Have you changed it at all?  Thanks.  
Helenice Chroniger

**Comment by Ecinele** [comment]
Hi Brian
I am a teacher in desperate need to send out the homework to my students.
The messages I send are close but not the same
I know in the past I sent different messages through your app
Have you changed it at all?
Is there anyway that you can show me how I can accomplish what I need to?
I truly appreciate your help.
Helenice Chroniger

**Comment by brismuth** [comment]
No, it hasn't changed significantly in a long time.
One of the extensions' users put together this video at one point, maybe that's what you had in mind.
https://www.youtube.com/watch?v=mVi7C9XpI6E&list=PL67064957837ACC70

**Comment by brismuth** [comment]
You can stick the {name} field anywhere you want in your text, and then you can put whatever you want into the name section next to the phone numbers to pipe that into your messages.

**Comment by Ecinele** [comment]
Hi Brian
This is not working at all
I tried to send the same message to 1 student
This is how it was set up
[image: image.png]
This is what I got. It was never sent to the second number
[image: image.png]

**Comment by Ecinele** [comment]
I really appreciate you look at this for me.
Thanks
Helenice Chroniger

**Comment by Ecinele** [comment]
I think I know what I did wrong.  I used a bracket instead of {}
Now...is there anyway that you can tweak this program to send multiple
messages to multiple numbers?
How much do you think you would charge for such a change?
Thanks
H. Chroniger

**Comment by brismuth** [comment]
It can already be used to send multiple messages to multiple people. Feel free to review the video I sent before.
