### ISSUE TITLE
manifest file is missing or unreadable

### ISSUE THREAD

**Issue by thisyeah** [brismuth/google-voice-bulk-texter#99]
![image](https://user-images.githubusercontent.com/57148082/67787802-6d421e00-fa2e-11e9-8235-8c4d4319cd94.png)
When I try to load the extension it says the manifest file is either missing or unreadable.

thank you

**Comment by brismuth** [comment]
It looks like you're trying to load the `google-voice-bulk-texter-master` folder instead of `google-voice-bulk-texter-master/src` folder. Please see the installation instructions and try again.

https://github.com/brismuth/google-voice-bulk-texter#install-it
